// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sharded

import (
	"context"
)

const getAccount = `-- name: GetAccount :one
SELECT id, tenant_id, display_name
FROM accounts
WHERE tenant_id = $1 AND id = $2
`

type GetAccountParams struct {
	TenantID int64
	ID       int64
}

// kind: read
// shard: tenant(tenant_id)
func (q *Queries) GetAccount(ctx context.Context, arg *GetAccountParams) (*Account, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.TenantID, arg.ID)
	var i Account
	err := row.Scan(&i.ID, &i.TenantID, &i.DisplayName)
	return &i, err
}

const updateAccountName = `-- name: UpdateAccountName :one
UPDATE accounts
SET display_name = $3
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, display_name
`

type UpdateAccountNameParams struct {
	TenantID    int64
	ID          int64
	DisplayName string
}

// kind: write
// shard: tenant(tenant_id)
func (q *Queries) UpdateAccountName(ctx context.Context, arg *UpdateAccountNameParams) (*Account, error) {
	row := q.db.QueryRow(ctx, updateAccountName, arg.TenantID, arg.ID, arg.DisplayName)
	var i Account
	err := row.Scan(&i.ID, &i.TenantID, &i.DisplayName)
	return &i, err
}

const upsertAccount = `-- name: UpsertAccount :one
INSERT INTO accounts (id, tenant_id, display_name)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE
SET tenant_id = EXCLUDED.tenant_id,
    display_name = EXCLUDED.display_name
RETURNING id, tenant_id, display_name
`

type UpsertAccountParams struct {
	ID          int64
	TenantID    int64
	DisplayName string
}

// kind: write
// shard: tenant(tenant_id)
func (q *Queries) UpsertAccount(ctx context.Context, arg *UpsertAccountParams) (*Account, error) {
	row := q.db.QueryRow(ctx, upsertAccount, arg.ID, arg.TenantID, arg.DisplayName)
	var i Account
	err := row.Scan(&i.ID, &i.TenantID, &i.DisplayName)
	return &i, err
}
