// Code generated by pgmesh. DO NOT EDIT.

package sharded

import (
	"context"
)

// readQuerier exposes generated read queries.
type readQuerier interface {
	// CountAccounts executes the generated CountAccounts query.
	CountAccounts(ctx context.Context, tenantID int64) (int64, error)
	// GetAccount executes the generated GetAccount query.
	GetAccount(ctx context.Context, arg *GetAccountParams) (*Account, error)
}

// writeQuerier exposes generated write queries.
type writeQuerier interface {
	// UpdateAccountName executes the generated UpdateAccountName query.
	UpdateAccountName(ctx context.Context, arg *UpdateAccountNameParams) (*Account, error)
	// UpsertAccount executes the generated UpsertAccount query.
	UpsertAccount(ctx context.Context, arg *UpsertAccountParams) (*Account, error)
}

// AccountsReader exposes read queries in the Accounts store group.
type AccountsReader interface {
	// GetAccount executes the generated GetAccount query.
	GetAccount(ctx context.Context, arg *GetAccountParams, storeOptions ...QueryOption) (*Account, error)
}

// AccountsWriter exposes write queries in the Accounts store group.
type AccountsWriter interface {
	// UpdateAccountName executes the generated UpdateAccountName query.
	UpdateAccountName(ctx context.Context, arg *UpdateAccountNameParams, storeOptions ...QueryOption) (*Account, error)
	// UpsertAccount executes the generated UpsertAccount query.
	UpsertAccount(ctx context.Context, arg *UpsertAccountParams, storeOptions ...QueryOption) (*Account, error)
}

// Accounts exposes all queries in its generated store group.
type Accounts interface {
	AccountsReader
	AccountsWriter
}

// ReportsReader exposes read queries in the Reports store group.
type ReportsReader interface {
	// CountAccounts executes the generated CountAccounts query.
	CountAccounts(ctx context.Context, tenantID int64, storeOptions ...QueryOption) (int64, error)
}

// ReportsWriter exposes write queries in the Reports store group.
type ReportsWriter interface {
}

// Reports exposes all queries in its generated store group.
type Reports interface {
	ReportsReader
	ReportsWriter
}

// Store is the topology-independent generated query API.
type Store interface {
	// Accounts returns the Accounts query group.
	Accounts() Accounts
	// Reports returns the Reports query group.
	Reports() Reports
}

var _ readQuerier = (*readQueries)(nil)
var _ writeQuerier = (*writeQueries)(nil)
var _ Querier = (*queryStore)(nil)

// ShardResolver resolves generated query parameters to shard keys.
type ShardResolver[SK any] interface {
	// Tenant resolves the "tenant" shard route.
	Tenant(tenantID int64) SK
}
