// Code generated by pgmesh. DO NOT EDIT.

package sharded

import (
	"context"
	"github.com/jackc/pgx/v5"
)

// readQueries exposes read-only generated queries.
type readQueries struct {
	main *Queries
}

func newReadQueries(q *Queries) *readQueries {
	return &readQueries{main: q}
}

// WithTx returns a read wrapper that executes queries through tx.
func (q *readQueries) WithTx(tx pgx.Tx) *readQueries {
	return newReadQueries(q.main.WithTx(tx))
}

// GetAccount executes the generated GetAccount query.
func (q *readQueries) GetAccount(ctx context.Context, arg *GetAccountParams) (*Account, error) {
	rv0, err := q.main.GetAccount(ctx, arg)
	if err != nil {
		var zero0 *Account
		return zero0, err
	}
	return rv0, nil
}
