// Code generated by pgmesh. DO NOT EDIT.

package sharded

import (
	"context"
	pgmesh "github.com/clnv/pgmesh"
)

// AccountsReader exposes read queries in the Accounts store group.
type AccountsReader interface {
	// GetAccount executes the generated GetAccount query.
	GetAccount(ctx context.Context, arg *GetAccountParams, storeOptions ...QueryOption) (*Account, error)
}

// AccountsWriter exposes write queries in the Accounts store group.
type AccountsWriter interface {
	// UpdateAccountName executes the generated UpdateAccountName query.
	UpdateAccountName(ctx context.Context, arg *UpdateAccountNameParams, storeOptions ...QueryOption) (*Account, error)
	// UpsertAccount executes the generated UpsertAccount query.
	UpsertAccount(ctx context.Context, arg *UpsertAccountParams, storeOptions ...QueryOption) (*Account, error)
}

// Accounts exposes all queries in its generated store group.
type Accounts interface {
	AccountsReader
	AccountsWriter
}

var _ Accounts = (*groupedMeshStore[uint8])(nil)

// Accounts returns the Accounts query group.
func (q *meshStore[SK]) Accounts() Accounts {
	return &groupedMeshStore[SK]{store: q}
}

// GetAccount executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) GetAccount(ctx context.Context, arg *GetAccountParams, storeOptions ...QueryOption) (result *Account, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Store", "GetAccount", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Transactional reads must use their transaction.
	if options.tx != nil {
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction, 0)
		return shard.Write().WithTx(options.tx).GetAccount(ctx, arg)
	}

	// Explicit primary reads bypass replicas.
	if options.primary {
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary, 0)
		return shard.Write().GetAccount(ctx, arg)
	}

	// Ordinary reads use the shard's replica route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead, 0)
	return shard.Read().GetAccount(ctx, arg)
}

// UpdateAccountName executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) UpdateAccountName(ctx context.Context, arg *UpdateAccountNameParams, storeOptions ...QueryOption) (result *Account, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Store", "UpdateAccountName", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	target := shard.Write()
	mode := pgmesh.RouteModePrimary
	writeMirrorCount := shard.WriteMirrorCount()
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
		writeMirrorCount = 0
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), mode, writeMirrorCount)
	return target.UpdateAccountName(ctx, arg)
}

// UpsertAccount executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) UpsertAccount(ctx context.Context, arg *UpsertAccountParams, storeOptions ...QueryOption) (result *Account, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Store", "UpsertAccount", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	target := shard.Write()
	mode := pgmesh.RouteModePrimary
	writeMirrorCount := shard.WriteMirrorCount()
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
		writeMirrorCount = 0
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), mode, writeMirrorCount)
	return target.UpsertAccount(ctx, arg)
}
