// Code generated by pgmesh. DO NOT EDIT.

package sharded

import (
	"context"
	"fmt"
	pgmesh "github.com/clnv/pgmesh"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
	"log/slog"
)

// ShardDatabaseConfig configures one primary and its read replicas.
type ShardDatabaseConfig struct {
	// Name uniquely identifies the physical replica set.
	Name string
	// Primary serves writes and primary reads. The caller owns its lifecycle.
	Primary DBTX
	// Replicas serve ordinary reads in round-robin order. The caller owns their lifecycles.
	Replicas []DBTX
}

// ShardedConfig configures shard routing behind the generated Store API.
type ShardedConfig[SK any] struct {
	// ReplicaSets define the physical database nodes in the topology.
	ReplicaSets []ShardDatabaseConfig
	// Shards maps every virtual shard to a primary replica set and ordered mirrors.
	Shards pgmesh.Shards
	// ShardHasher maps resolved shard keys to virtual shard indexes.
	ShardHasher pgmesh.ShardHasher[SK]
	// Resolver extracts application shard keys from generated query parameters.
	Resolver ShardResolver[SK]
	// TracerProvider records routed query spans; nil uses the global provider.
	TracerProvider trace.TracerProvider
	// MeterProvider records routed query metrics; nil uses the global provider.
	MeterProvider metric.MeterProvider
	// Logger receives routed query debug logs; nil disables logging.
	Logger *slog.Logger
}

type shardedStoreConfig[SK any] struct{ config ShardedConfig[SK] }

// Sharded returns an opaque sharded topology configuration.
func Sharded[SK any](config ShardedConfig[SK]) StoreConfig {
	return shardedStoreConfig[SK]{config: config}
}

func (c shardedStoreConfig[SK]) buildStore(ctx context.Context) (Store, error) {
	config := c.config
	if config.Resolver == nil {
		return nil, fmt.Errorf("pgmesh: shard resolver is nil")
	}
	nodes := make(map[string]DBTX)
	specs := make([]pgmesh.ReplicaSetSpec, 0, len(config.ReplicaSets))
	for setIndex, set := range config.ReplicaSets {
		primaryDSN := fmt.Sprintf("pgmesh-internal://%d/primary", setIndex)
		nodes[primaryDSN] = set.Primary
		replicas := make([]pgmesh.Connection, 0, len(set.Replicas))
		for replicaIndex, database := range set.Replicas {
			dsn := fmt.Sprintf("pgmesh-internal://%d/replica/%d", setIndex, replicaIndex)
			nodes[dsn] = database
			replicas = append(replicas, pgmesh.Connection{DSN: dsn})
		}
		specs = append(specs, pgmesh.ReplicaSetSpec{
			Name:     set.Name,
			Primary:  pgmesh.Connection{DSN: primaryDSN},
			Replicas: replicas,
		})
	}
	mesh, err := pgmesh.CreateMesh(ctx, &pgmesh.Options[*readQueries, *queryStore, SK]{
		ReplicaSets: specs,
		Shards:      config.Shards,
		CreateNode: func(_ context.Context, dsn string) (pgmesh.Node[*readQueries, *queryStore], error) {
			database, ok := nodes[dsn]
			if !ok || database == nil {
				return pgmesh.Node[*readQueries, *queryStore]{}, fmt.Errorf("pgmesh: database node %q is nil", dsn)
			}
			return newStoreNode(database), nil
		},
		ShardHasher:    config.ShardHasher,
		TracerProvider: config.TracerProvider,
		MeterProvider:  config.MeterProvider,
		Logger:         config.Logger,
	})
	if err != nil {
		return nil, err
	}
	return &meshStore[SK]{mesh: mesh, resolver: config.Resolver}, nil
}
