// Code generated by pgmesh. DO NOT EDIT.

package store

import (
	"context"
	db "github.com/clnv/pgmesh/tests/generate/separate_package/internal"
)

// Analysis re-exports Analysis from the sqlc package.
type Analysis = db.Analysis

// AnalysisState re-exports AnalysisState from the sqlc package.
type AnalysisState = db.AnalysisState

// CreateUserParams re-exports CreateUserParams from the sqlc package.
type CreateUserParams = db.CreateUserParams

// GetAnalysisParams re-exports GetAnalysisParams from the sqlc package.
type GetAnalysisParams = db.GetAnalysisParams

// GetTenantUserAnalysisParams re-exports GetTenantUserAnalysisParams from the sqlc package.
type GetTenantUserAnalysisParams = db.GetTenantUserAnalysisParams

// GetTenantUserAnalysisRow re-exports GetTenantUserAnalysisRow from the sqlc package.
type GetTenantUserAnalysisRow = db.GetTenantUserAnalysisRow

// GetUserParams re-exports GetUserParams from the sqlc package.
type GetUserParams = db.GetUserParams

// ListP2PMessageIDsByChatParams re-exports ListP2PMessageIDsByChatParams from the sqlc package.
type ListP2PMessageIDsByChatParams = db.ListP2PMessageIDsByChatParams

// ListP2PMessagesByChatParams re-exports ListP2PMessagesByChatParams from the sqlc package.
type ListP2PMessagesByChatParams = db.ListP2PMessagesByChatParams

// Message re-exports Message from the sqlc package.
type Message = db.Message

// NullAnalysisState re-exports NullAnalysisState from the sqlc package.
type NullAnalysisState = db.NullAnalysisState

// UpdateUserNameParams re-exports UpdateUserNameParams from the sqlc package.
type UpdateUserNameParams = db.UpdateUserNameParams

// User re-exports User from the sqlc package.
type User = db.User

// readQuerier exposes generated read queries.
type readQuerier interface {
	// GetAnalysis executes the generated GetAnalysis query.
	GetAnalysis(ctx context.Context, arg *db.GetAnalysisParams) (*db.Analysis, error)
	// GetTenantUserAnalysis executes the generated GetTenantUserAnalysis query.
	GetTenantUserAnalysis(ctx context.Context, arg *db.GetTenantUserAnalysisParams) (*db.GetTenantUserAnalysisRow, error)
	// GetUser executes the generated GetUser query.
	GetUser(ctx context.Context, arg *db.GetUserParams) (*db.User, error)
	// ListP2PMessageIDsByChat executes the generated ListP2PMessageIDsByChat query.
	ListP2PMessageIDsByChat(ctx context.Context, arg *db.ListP2PMessageIDsByChatParams) ([]interface{}, error)
	// ListP2PMessagesByChat executes the generated ListP2PMessagesByChat query.
	ListP2PMessagesByChat(ctx context.Context, arg *db.ListP2PMessagesByChatParams) ([]*db.Message, error)
}

// writeQuerier exposes generated write queries.
type writeQuerier interface {
	// CreateUser executes the generated CreateUser query.
	CreateUser(ctx context.Context, arg *db.CreateUserParams) (*db.User, error)
	// UpdateUserName executes the generated UpdateUserName query.
	UpdateUserName(ctx context.Context, arg *db.UpdateUserNameParams) (*db.User, error)
}

// GetTenantUserAnalysisShardParams carries the sqlc argument and routing-only shard parameters for GetTenantUserAnalysis.
type GetTenantUserAnalysisShardParams struct {
	Arg      *GetTenantUserAnalysisParams
	TenantID int64
}

// ListP2PMessageIDsByChatShardParams carries the sqlc argument and routing-only shard parameters for ListP2PMessageIDsByChat.
type ListP2PMessageIDsByChatShardParams struct {
	Arg             *ListP2PMessageIDsByChatParams
	ToUserOrGroupID int64
	InGroup         bool
}

// ListP2PMessagesByChatShardParams carries the sqlc argument and routing-only shard parameters for ListP2PMessagesByChat.
type ListP2PMessagesByChatShardParams struct {
	Arg             *ListP2PMessagesByChatParams
	ToUserOrGroupID int64
	InGroup         bool
}

// AnalysesReader exposes read queries in the Analyses store group.
type AnalysesReader interface {
	// GetAnalysis executes the generated GetAnalysis query.
	GetAnalysis(ctx context.Context, arg *GetAnalysisParams, storeOptions ...QueryOption) (*Analysis, error)
	// GetTenantUserAnalysis executes the generated GetTenantUserAnalysis query.
	GetTenantUserAnalysis(ctx context.Context, arg *GetTenantUserAnalysisShardParams, storeOptions ...QueryOption) (*GetTenantUserAnalysisRow, error)
}

// AnalysesWriter exposes write queries in the Analyses store group.
type AnalysesWriter interface {
}

// Analyses exposes all queries in its generated store group.
type Analyses interface {
	AnalysesReader
	AnalysesWriter
}

// QueryMessageReader exposes read queries in the QueryMessage store group.
type QueryMessageReader interface {
	// ListP2PMessageIDsByChat executes the generated ListP2PMessageIDsByChat query.
	ListP2PMessageIDsByChat(ctx context.Context, arg *ListP2PMessageIDsByChatShardParams, storeOptions ...QueryOption) ([]interface{}, error)
	// ListP2PMessagesByChat executes the generated ListP2PMessagesByChat query.
	ListP2PMessagesByChat(ctx context.Context, arg *ListP2PMessagesByChatShardParams, storeOptions ...QueryOption) ([]*Message, error)
}

// QueryMessageWriter exposes write queries in the QueryMessage store group.
type QueryMessageWriter interface {
}

// QueryMessage exposes all queries in its generated store group.
type QueryMessage interface {
	QueryMessageReader
	QueryMessageWriter
}

// UsersReader exposes read queries in the Users store group.
type UsersReader interface {
	// GetUser executes the generated GetUser query.
	GetUser(ctx context.Context, arg *GetUserParams, storeOptions ...QueryOption) (*User, error)
}

// UsersWriter exposes write queries in the Users store group.
type UsersWriter interface {
	// CreateUser executes the generated CreateUser query.
	CreateUser(ctx context.Context, arg *CreateUserParams, storeOptions ...QueryOption) (*User, error)
	// UpdateUserName executes the generated UpdateUserName query.
	UpdateUserName(ctx context.Context, arg *UpdateUserNameParams, storeOptions ...QueryOption) (*User, error)
}

// Users exposes all queries in its generated store group.
type Users interface {
	UsersReader
	UsersWriter
}

// Store is the topology-independent generated query API.
type Store interface {
	// Analyses returns the Analyses query group.
	Analyses() Analyses
	// QueryMessage returns the QueryMessage query group.
	QueryMessage() QueryMessage
	// Users returns the Users query group.
	Users() Users
}

var _ readQuerier = (*readQueries)(nil)
var _ writeQuerier = (*writeQueries)(nil)
var _ db.Querier = (*queryStore)(nil)

// ShardResolver resolves generated query parameters to shard keys.
type ShardResolver[SK any] interface {
	// Messagekey resolves the "messageKey" shard route.
	Messagekey(userID int64, toUserOrGroupID int64, inGroup bool) SK
	// Tenant resolves the "tenant" shard route.
	Tenant(tenantID int64) SK
}
