// Package pgmesh provides type-safe replica routing and virtual sharding for
// query wrappers generated by the pgmesh process plugin.
//
// Mesh values are immutable after construction and may be shared by concurrent
// callers when their configured nodes are concurrency-safe. Applications own
// database pools, loggers, and OpenTelemetry providers; pgmesh does not close
// or shut them down.
package pgmesh
