package sqlcplugin

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"go/types"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/jinzhu/inflection"
	"github.com/sqlc-dev/plugin-sdk-go/plugin"
)

const (
	defaultOutputFileName = "store_querier.go"
	defaultPackageName    = "db"
	defaultSQLPackage     = "pgx/v5"
	defaultDatabaseSQL    = "database/sql"
	defaultErrorsPackage  = "errors"
	defaultReadInterface  = "ReadQuerier"
	defaultWriteInterface = "WriteQuerier"
	defaultStoreInterface = "StoreQuerier"
	defaultReadType       = "ReadQueries"
	defaultWriteType      = "WriteQueries"
	defaultTargetType     = "Queries"
	defaultTargetNew      = "New"
	defaultReceiverName   = "q"
	defaultPGXPackage     = "github.com/jackc/pgx/v5"
	defaultRuntimePackage = "github.com/clnv/pgmesh"
	defaultNodeNew        = "NewStoreNode"
	defaultResolver       = "ShardResolver"
	defaultShardedType    = "ShardedQueries"
	defaultShardedNew     = "NewShardedQueries"
	generatedHeader       = "// Code generated by pgmesh. DO NOT EDIT."
	mirrorReceiverName    = "mirror"
	mirrorErrorName       = "mirrorErr"
	resultErrorName       = "error"
	cmdCopyFrom           = ":copyfrom"
	emptyInterfaceType    = "interface{}"
)

// Options are the sqlc plugin options for the store wrapper generator.
type Options struct {
	// OutputFileName is the generated Go file name.
	OutputFileName string `json:"output_file_name"`
	// SourcePackage is the package containing the source query types.
	SourcePackage string `json:"source_package"`

	// PackageName is the package clause used in generated code.
	PackageName string `json:"package"`
	// InternalImportPath imports sqlc output when wrappers use a separate package.
	InternalImportPath string `json:"internal_import_path"`
	// InternalImportAlias overrides the imported sqlc package qualifier.
	InternalImportAlias string `json:"internal_import_alias"`
	// InterfaceName is the sqlc-generated interface the store must implement.
	InterfaceName string `json:"interface"`
	// TypeName is the combined read-write wrapper type name.
	TypeName string `json:"type"`
	// TargetTypeName is the sqlc-generated query type name.
	TargetTypeName string `json:"target_type"`
	// ConstructorName is the combined wrapper constructor name.
	ConstructorName string `json:"constructor"`
	// TargetConstructorName is the sqlc-generated query constructor name.
	TargetConstructorName string `json:"target_constructor"`
	// ReceiverName is the receiver identifier used by generated methods.
	ReceiverName string `json:"receiver"`
	// SkipWithTx requests omission of transaction methods and is currently unsupported.
	SkipWithTx bool `json:"skip_with_tx"`
	// IgnoreMirrorError makes generated writes discard non-NoRows mirror errors.
	IgnoreMirrorError bool `json:"ignore_mirror_error"`
	// ReadInterfaceName is the generated read-only interface name.
	ReadInterfaceName string `json:"read_interface"`
	// WriteInterfaceName is the generated write interface name.
	WriteInterfaceName string `json:"write_interface"`
	// StoreInterfaceName is the generated combined query interface name.
	StoreInterfaceName string `json:"store_interface"`
	// ReadTypeName is the generated read-only wrapper type name.
	ReadTypeName string `json:"read_type"`
	// WriteTypeName is the generated primary-capable wrapper type name.
	WriteTypeName string `json:"write_type"`
	// ReadConstructorName is the read-only wrapper constructor name.
	ReadConstructorName string `json:"read_constructor"`
	// WriteConstructorName is the primary-capable wrapper constructor name.
	WriteConstructorName string `json:"write_constructor"`
	// RuntimeImportPath is the import path for the pgmesh runtime package.
	RuntimeImportPath string `json:"runtime_import_path"`
	// NodeConstructorName is the generated database node constructor name.
	NodeConstructorName string `json:"node_constructor"`
	// ResolverInterfaceName is the generated shard resolver interface name.
	ResolverInterfaceName string `json:"resolver_interface"`
	// ShardedTypeName is the generated routed facade type name.
	ShardedTypeName string `json:"sharded_type"`
	// ShardedConstructor is the routed facade constructor name.
	ShardedConstructor string `json:"sharded_constructor"`

	// SQLPackage selects the sqlc database driver; only pgx/v5 is supported.
	SQLPackage string `json:"sql_package"`
	// QueryParameterLimit matches sqlc's threshold for generating parameter structs.
	QueryParameterLimit *int32 `json:"query_parameter_limit"`
	// EmitParamsStructPointers matches sqlc's parameter-struct pointer setting.
	EmitParamsStructPointers bool `json:"emit_params_struct_pointers"`
	// EmitResultStructPointers matches sqlc's result-struct pointer setting.
	EmitResultStructPointers bool `json:"emit_result_struct_pointers"`
	// EmitPointersForNullTypes matches sqlc's nullable-type pointer setting.
	EmitPointersForNullTypes bool `json:"emit_pointers_for_null_types"`
	// EmitPointersForNullEnumType overrides pointer emission for nullable enums.
	EmitPointersForNullEnumType *bool `json:"emit_pointers_for_null_enum_types"`
	// EmitExactTableNames preserves table names when deriving generated Go types.
	EmitExactTableNames bool `json:"emit_exact_table_names"`
	// Rename maps SQL identifiers to generated Go identifiers.
	Rename map[string]string `json:"rename"`
	// Overrides applies sqlc-compatible database and column type overrides.
	Overrides []override `json:"overrides"`
}

// Generate implements sqlc's CodegenService.Generate hook.
func Generate(_ context.Context, req *plugin.GenerateRequest) (*plugin.GenerateResponse, error) {
	opts, err := parseOptions(req)
	if err != nil {
		return nil, err
	}

	queries, imports, err := querySpecs(req, opts)
	if err != nil {
		return nil, err
	}

	content, err := generateWrapper(opts, queries, imports)
	if err != nil {
		return nil, err
	}
	return &plugin.GenerateResponse{
		Files: []*plugin.File{{
			Name:     opts.OutputFileName,
			Contents: content,
		}},
	}, nil
}

func parseOptions(req *plugin.GenerateRequest) (*Options, error) {
	if req.GetSettings().GetEngine() != "postgresql" {
		return nil, fmt.Errorf(
			"engine %q is unsupported; pgmesh v1 requires postgresql",
			req.GetSettings().GetEngine(),
		)
	}
	opts := &Options{} //nolint:exhaustruct // Populated from JSON and normalized with defaults below.
	if len(req.GetPluginOptions()) > 0 {
		if err := json.Unmarshal(req.GetPluginOptions(), opts); err != nil {
			return nil, fmt.Errorf("unmarshal plugin options: %w", err)
		}
	}

	if opts.OutputFileName == "" {
		opts.OutputFileName = defaultOutputFileName
	}
	if opts.PackageName == "" {
		opts.PackageName = outputPackageName(req)
	}
	if opts.SourcePackage == "" {
		opts.SourcePackage = opts.PackageName
	}
	if opts.SQLPackage == "" {
		opts.SQLPackage = defaultSQLPackage
	}
	if opts.QueryParameterLimit == nil {
		limit := int32(1)
		opts.QueryParameterLimit = &limit
	}
	if opts.TypeName == "" {
		opts.TypeName = storeTypeName(opts)
	}
	if opts.TargetTypeName == "" {
		opts.TargetTypeName = defaultTargetType
	}
	if opts.TargetConstructorName == "" {
		opts.TargetConstructorName = defaultTargetNew
	}
	if opts.ConstructorName == "" {
		opts.ConstructorName = "New" + opts.TypeName
	}
	if opts.ReceiverName == "" {
		opts.ReceiverName = defaultReceiverName
	}
	if opts.ReadInterfaceName == "" {
		opts.ReadInterfaceName = defaultReadInterface
	}
	if opts.WriteInterfaceName == "" {
		opts.WriteInterfaceName = defaultWriteInterface
	}
	if opts.StoreInterfaceName == "" {
		opts.StoreInterfaceName = defaultStoreInterface
	}
	if opts.ReadTypeName == "" {
		opts.ReadTypeName = defaultReadType
	}
	if opts.WriteTypeName == "" {
		opts.WriteTypeName = defaultWriteType
	}
	if opts.ReadConstructorName == "" {
		opts.ReadConstructorName = "New" + opts.ReadTypeName
	}
	if opts.WriteConstructorName == "" {
		opts.WriteConstructorName = "New" + opts.WriteTypeName
	}
	if opts.RuntimeImportPath == "" {
		opts.RuntimeImportPath = defaultRuntimePackage
	}
	if opts.NodeConstructorName == "" {
		opts.NodeConstructorName = defaultNodeNew
	}
	if opts.ResolverInterfaceName == "" {
		opts.ResolverInterfaceName = defaultResolver
	}
	if opts.ShardedTypeName == "" {
		opts.ShardedTypeName = defaultShardedType
	}
	if opts.ShardedConstructor == "" {
		opts.ShardedConstructor = defaultShardedNew
	}
	if *opts.QueryParameterLimit < 0 {
		return nil, errors.New("query parameter limit must not be negative")
	}
	if opts.SQLPackage != string(sqlDriverPGXV5) {
		return nil, fmt.Errorf("sql_package %q is unsupported; pgmesh v1 requires pgx/v5", opts.SQLPackage)
	}
	if opts.SkipWithTx {
		return nil, errors.New("skip_with_tx is unsupported; pgmesh requires generated pgx/v5 transaction support")
	}

	for idx := range opts.Overrides {
		if err := opts.Overrides[idx].parse(req); err != nil {
			return nil, fmt.Errorf("parse override %d: %w", idx, err)
		}
	}

	return opts, nil
}

func outputPackageName(req *plugin.GenerateRequest) string {
	if codegen := req.GetSettings().GetCodegen(); codegen != nil && codegen.GetOut() != "" {
		name := filepath.Base(codegen.GetOut())
		if validRouteIdentifier(name) && !goKeywords[name] {
			return name
		}
	}
	return defaultPackageName
}

type importSpec struct {
	name string
	path string
}

type importSet struct {
	byPath map[string]importSpec
}

func newImportSet() *importSet {
	return &importSet{byPath: map[string]importSpec{}}
}

func (s *importSet) add(path string) {
	s.addNamed("", path)
}

func (s *importSet) addNamed(name, path string) {
	if path == "" {
		return
	}
	s.byPath[path] = importSpec{name: name, path: path}
}

func (s *importSet) addForType(typ string) {
	for qualifier, path := range knownSelectorImports {
		if typeUsesQualifier(typ, qualifier) {
			s.add(path)
		}
	}
}

func (s *importSet) sorted() []importSpec {
	imports := make([]importSpec, 0, len(s.byPath))
	for _, imp := range s.byPath {
		imports = append(imports, imp)
	}
	sort.Slice(imports, func(i, j int) bool {
		if imports[i].path == imports[j].path {
			return imports[i].name < imports[j].name
		}
		return imports[i].path < imports[j].path
	})
	return imports
}

var knownSelectorImports = map[string]string{
	"driver":   "database/sql/driver",
	"context":  "context",
	"json":     "encoding/json",
	"net":      "net",
	"netip":    "net/netip",
	"sql":      "database/sql",
	"time":     "time",
	"uuid":     "github.com/google/uuid",
	"pgconn":   "github.com/jackc/pgx/v5/pgconn",
	"pgtype":   "github.com/jackc/pgx/v5/pgtype",
	"pgvector": "github.com/pgvector/pgvector-go",
	"pqtype":   "github.com/sqlc-dev/pqtype",
}

func typeUsesQualifier(typ, qualifier string) bool {
	return strings.Contains(typ, qualifier+".") || strings.Contains(typ, "*"+qualifier+".") ||
		strings.Contains(typ, "[]"+qualifier+".")
}

type typeResolver struct {
	req     *plugin.GenerateRequest
	opts    *Options
	imports *importSet
}

func querySpecs(req *plugin.GenerateRequest, opts *Options) ([]generatedQuery, *importSet, error) {
	resolver := &typeResolver{
		req:     req,
		opts:    opts,
		imports: newImportSet(),
	}
	structs := buildStructs(req, opts, resolver)
	queries, err := buildQueries(req, opts, resolver, structs)
	if err != nil {
		return nil, nil, err
	}
	return queries, resolver.imports, nil
}

func generateWrapper(opts *Options, queries []generatedQuery, imports *importSet) ([]byte, error) {
	routes, err := collectShardRoutes(queries)
	if err != nil {
		return nil, err
	}
	if opts.InternalImportPath != "" {
		imports.addNamed(importAlias(opts.InternalImportAlias), opts.InternalImportPath)
	}
	imports.addNamed("pgmesh", opts.RuntimeImportPath)
	if !opts.SkipWithTx {
		imports.add(defaultPGXPackage)
	}
	if !opts.IgnoreMirrorError {
		imports.add(defaultDatabaseSQL)
		imports.add(defaultErrorsPackage)
	}

	var out bytes.Buffer
	fmt.Fprintf(&out, "%s\n\n", generatedHeader)
	fmt.Fprintf(&out, "package %s\n\n", opts.PackageName)
	writeImports(&out, imports.sorted())

	writeSplitInterface(&out, opts.ReadInterfaceName, queries, queryKindRead)
	writeSplitInterface(&out, opts.WriteInterfaceName, queries, queryKindWrite)
	fmt.Fprintf(&out, "// %s combines the generated read and write query interfaces.\n", opts.StoreInterfaceName)
	fmt.Fprintf(&out, "type %s interface {\n", opts.StoreInterfaceName)
	fmt.Fprintf(&out, "\t%s\n", opts.ReadInterfaceName)
	fmt.Fprintf(&out, "\t%s\n", opts.WriteInterfaceName)
	out.WriteString("}\n\n")

	fmt.Fprintf(&out, "var _ %s = (*%s)(nil)\n", opts.ReadInterfaceName, opts.ReadTypeName)
	fmt.Fprintf(&out, "var _ %s = (*%s)(nil)\n", opts.WriteInterfaceName, opts.WriteTypeName)
	fmt.Fprintf(&out, "var _ %s = (*%s)(nil)\n", opts.StoreInterfaceName, opts.TypeName)
	fmt.Fprintf(&out, "var _ %s = (*%s)(nil)\n\n", interfaceName(opts), opts.TypeName)

	writeReadQueries(&out, opts, queries)
	writeWriteQueries(&out, opts, queries)
	writeStoreQueries(&out, opts)
	writeNodeConstructor(&out, opts)
	if len(routes) > 0 {
		writeShardedQueries(&out, opts, queries, routes)
	}

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated wrapper: %w", err)
	}
	return formatted, nil
}

func writeReadQueries(out *bytes.Buffer, opts *Options, queries []generatedQuery) {
	fmt.Fprintf(out, "// %s exposes read-only generated queries.\n", opts.ReadTypeName)
	fmt.Fprintf(out, "type %s struct {\n", opts.ReadTypeName)
	fmt.Fprintf(out, "\tmain *%s\n", targetName(opts, opts.TargetTypeName))
	out.WriteString("}\n\n")

	fmt.Fprintf(out, "// %s creates a read-only query wrapper.\n", opts.ReadConstructorName)
	fmt.Fprintf(out, "func %s(database %s) *%s {\n", opts.ReadConstructorName, targetName(opts, "DBTX"), opts.ReadTypeName)
	fmt.Fprintf(
		out,
		"\treturn %s(%s(database))\n",
		privateConstructorName(opts.ReadConstructorName),
		targetName(opts, opts.TargetConstructorName),
	)
	out.WriteString("}\n\n")

	fmt.Fprintf(
		out,
		"func %s(q *%s) *%s {\n",
		privateConstructorName(opts.ReadConstructorName),
		targetName(opts, opts.TargetTypeName),
		opts.ReadTypeName,
	)
	fmt.Fprintf(out, "\treturn &%s{main: q}\n", opts.ReadTypeName)
	out.WriteString("}\n\n")

	if !opts.SkipWithTx {
		out.WriteString("// WithTx returns a read wrapper that executes queries through tx.\n")
		fmt.Fprintf(out, "func (%s *%s) WithTx(tx pgx.Tx) *%s {\n", opts.ReceiverName, opts.ReadTypeName, opts.ReadTypeName)
		fmt.Fprintf(out, "\treturn %s(%s.main.WithTx(tx))\n", privateConstructorName(opts.ReadConstructorName), opts.ReceiverName)
		out.WriteString("}\n\n")
	}

	writeQueryMethods(out, opts, opts.ReadTypeName, queries, queryKindRead, false)
}

func writeWriteQueries(out *bytes.Buffer, opts *Options, queries []generatedQuery) {
	fmt.Fprintf(out, "// %s exposes primary-capable generated queries.\n", opts.WriteTypeName)
	fmt.Fprintf(out, "type %s struct {\n", opts.WriteTypeName)
	fmt.Fprintf(out, "\tmain *%s\n", targetName(opts, opts.TargetTypeName))
	fmt.Fprintf(out, "\tmirrors []*%s\n", targetName(opts, opts.TargetTypeName))
	out.WriteString("}\n\n")

	fmt.Fprintf(out, "// %s creates a primary-capable query wrapper.\n", opts.WriteConstructorName)
	fmt.Fprintf(out, "func %s(database %s) *%s {\n", opts.WriteConstructorName, targetName(opts, "DBTX"), opts.WriteTypeName)
	fmt.Fprintf(
		out,
		"\treturn %s(%s(database))\n",
		privateConstructorName(opts.WriteConstructorName),
		targetName(opts, opts.TargetConstructorName),
	)
	out.WriteString("}\n\n")

	fmt.Fprintf(
		out,
		"func %s(q *%s, mirrors ...*%s) *%s {\n",
		privateConstructorName(opts.WriteConstructorName),
		targetName(opts, opts.TargetTypeName),
		targetName(opts, opts.TargetTypeName),
		opts.WriteTypeName,
	)
	fmt.Fprintf(out, "\treturn &%s{main: q, mirrors: mirrors}\n", opts.WriteTypeName)
	out.WriteString("}\n\n")

	if !opts.SkipWithTx {
		out.WriteString("// WithTx returns a write wrapper that executes queries through tx.\n")
		fmt.Fprintf(out, "func (%s *%s) WithTx(tx pgx.Tx) *%s {\n", opts.ReceiverName, opts.WriteTypeName, opts.WriteTypeName)
		fmt.Fprintf(out, "\treturn %s(%s.main.WithTx(tx))\n", privateConstructorName(opts.WriteConstructorName), opts.ReceiverName)
		out.WriteString("}\n\n")
	}

	out.WriteString("// WithMirrors returns a copy that also writes to the supplied mirrors.\n")
	fmt.Fprintf(
		out,
		"func (%s *%s) WithMirrors(qs ...*%s) *%s {\n",
		opts.ReceiverName,
		opts.WriteTypeName,
		opts.WriteTypeName,
		opts.WriteTypeName,
	)
	fmt.Fprintf(out, "\tvar mirrors []*%s\n", targetName(opts, opts.TargetTypeName))
	fmt.Fprintf(out, "\tmirrors = append(mirrors, %s.mirrors...)\n", opts.ReceiverName)
	out.WriteString("\tfor _, mirror := range qs {\n")
	out.WriteString("\t\tif mirror == nil {\n")
	out.WriteString("\t\t\tcontinue\n")
	out.WriteString("\t\t}\n")
	out.WriteString("\t\tmirrors = append(mirrors, mirror.main)\n")
	out.WriteString("\t\tmirrors = append(mirrors, mirror.mirrors...)\n")
	out.WriteString("\t}\n")
	fmt.Fprintf(out, "\treturn %s(%s.main, mirrors...)\n", privateConstructorName(opts.WriteConstructorName), opts.ReceiverName)
	out.WriteString("}\n\n")

	fmt.Fprintf(
		out,
		"func (%s *%s) mirror(fn func(*%s) error) error {\n",
		opts.ReceiverName,
		opts.WriteTypeName,
		targetName(opts, opts.TargetTypeName),
	)
	fmt.Fprintf(out, "\tfor _, mirror := range %s.mirrors {\n", opts.ReceiverName)
	out.WriteString("\t\tif err := fn(mirror); err != nil {\n")
	if opts.IgnoreMirrorError {
		out.WriteString("\t\t\tcontinue\n")
	} else {
		out.WriteString("\t\t\tif errors.Is(err, sql.ErrNoRows) {\n")
		out.WriteString("\t\t\t\tcontinue\n")
		out.WriteString("\t\t\t}\n")
		out.WriteString("\t\t\treturn err\n")
	}
	out.WriteString("\t\t}\n")
	out.WriteString("\t}\n")
	out.WriteString("\treturn nil\n")
	out.WriteString("}\n\n")

	writeQueryMethods(out, opts, opts.WriteTypeName, queries, queryKindWrite, true)
}

func writeStoreQueries(out *bytes.Buffer, opts *Options) {
	fmt.Fprintf(out, "// %s combines read-only and primary-capable generated queries.\n", opts.TypeName)
	fmt.Fprintf(out, "type %s struct {\n", opts.TypeName)
	fmt.Fprintf(out, "\t*%s\n", opts.ReadTypeName)
	fmt.Fprintf(out, "\t*%s\n", opts.WriteTypeName)
	out.WriteString("}\n\n")

	fmt.Fprintf(out, "// %s creates a combined query wrapper.\n", opts.ConstructorName)
	fmt.Fprintf(out, "func %s(database %s) *%s {\n", opts.ConstructorName, targetName(opts, "DBTX"), opts.TypeName)
	fmt.Fprintf(
		out,
		"\treturn %s(%s(database))\n",
		privateConstructorName(opts.ConstructorName),
		targetName(opts, opts.TargetConstructorName),
	)
	out.WriteString("}\n\n")

	fmt.Fprintf(
		out,
		"func %s(q *%s, mirrors ...*%s) *%s {\n",
		privateConstructorName(opts.ConstructorName),
		targetName(opts, opts.TargetTypeName),
		targetName(opts, opts.TargetTypeName),
		opts.TypeName,
	)
	fmt.Fprintf(out, "\treturn &%s{\n", opts.TypeName)
	fmt.Fprintf(out, "\t\t%s:  %s(q),\n", opts.ReadTypeName, privateConstructorName(opts.ReadConstructorName))
	fmt.Fprintf(out, "\t\t%s: %s(q, mirrors...),\n", opts.WriteTypeName, privateConstructorName(opts.WriteConstructorName))
	out.WriteString("\t}\n")
	out.WriteString("}\n\n")

	if !opts.SkipWithTx {
		out.WriteString("// WithTx returns a store wrapper that executes queries through tx.\n")
		fmt.Fprintf(out, "func (%s *%s) WithTx(tx pgx.Tx) *%s {\n", opts.ReceiverName, opts.TypeName, opts.TypeName)
		fmt.Fprintf(
			out,
			"\treturn %s(%s.%s.main.WithTx(tx))\n",
			privateConstructorName(opts.ConstructorName),
			opts.ReceiverName,
			opts.WriteTypeName,
		)
		out.WriteString("}\n\n")
	}

	out.WriteString("// WithMirrors returns a copy that also writes to the supplied mirrors.\n")
	fmt.Fprintf(out, "func (%s *%s) WithMirrors(qs ...*%s) *%s {\n", opts.ReceiverName, opts.TypeName, opts.TypeName, opts.TypeName)
	fmt.Fprintf(out, "\tvar mirrors []*%s\n", targetName(opts, opts.TargetTypeName))
	fmt.Fprintf(out, "\tmirrors = append(mirrors, %s.%s.mirrors...)\n", opts.ReceiverName, opts.WriteTypeName)
	out.WriteString("\tfor _, mirror := range qs {\n")
	fmt.Fprintf(out, "\t\tif mirror == nil || mirror.%s == nil {\n", opts.WriteTypeName)
	out.WriteString("\t\t\tcontinue\n")
	out.WriteString("\t\t}\n")
	fmt.Fprintf(out, "\t\tmirrors = append(mirrors, mirror.%s.main)\n", opts.WriteTypeName)
	fmt.Fprintf(out, "\t\tmirrors = append(mirrors, mirror.%s.mirrors...)\n", opts.WriteTypeName)
	out.WriteString("\t}\n")
	fmt.Fprintf(
		out,
		"\treturn %s(%s.%s.main, mirrors...)\n",
		privateConstructorName(opts.ConstructorName),
		opts.ReceiverName,
		opts.WriteTypeName,
	)
	out.WriteString("}\n\n")
}

func writeNodeConstructor(out *bytes.Buffer, opts *Options) {
	fmt.Fprintf(out, "// %s creates a pgmesh node backed by database.\n", opts.NodeConstructorName)
	fmt.Fprintf(
		out,
		"func %s(database %s) pgmesh.Node[*%s, *%s] {\n",
		opts.NodeConstructorName,
		targetName(opts, "DBTX"),
		opts.ReadTypeName,
		opts.TypeName,
	)
	fmt.Fprintf(out, "\tqueries := %s(database)\n", targetName(opts, opts.TargetConstructorName))
	fmt.Fprintf(
		out,
		"\treturn pgmesh.NewNode(%s(queries), %s(queries))\n",
		privateConstructorName(opts.ReadConstructorName),
		privateConstructorName(opts.ConstructorName),
	)
	out.WriteString("}\n\n")
}

func writeShardedQueries(
	out *bytes.Buffer,
	opts *Options,
	queries []generatedQuery,
	routes []shardRoute,
) {
	fmt.Fprintf(out, "// %s resolves generated query parameters to shard keys.\n", opts.ResolverInterfaceName)
	fmt.Fprintf(out, "type %s[SK any] interface {\n", opts.ResolverInterfaceName)
	for _, route := range routes {
		fmt.Fprintf(out, "\t// %s resolves the %q shard route.\n", route.methodName, route.name)
		fmt.Fprintf(out, "\t%s(%s) SK\n", route.methodName, routeOperandsSignature(route.operands))
	}
	out.WriteString("}\n\n")

	out.WriteString("type routeOptions struct {\n")
	out.WriteString("\tprimary bool\n")
	out.WriteString("\ttx pgx.Tx\n")
	out.WriteString("}\n\n")
	out.WriteString("// RouteOption customizes routing for one generated query call.\n")
	out.WriteString("type RouteOption func(*routeOptions)\n\n")
	out.WriteString("// ReadFromPrimary routes a read query to the shard's primary.\n")
	out.WriteString("func ReadFromPrimary() RouteOption {\n")
	out.WriteString("\treturn func(options *routeOptions) { options.primary = true }\n")
	out.WriteString("}\n\n")
	out.WriteString("// WithTx routes a query through tx and suppresses write mirrors.\n")
	out.WriteString("func WithTx(tx pgx.Tx) RouteOption {\n")
	out.WriteString("\treturn func(options *routeOptions) { options.tx = tx }\n")
	out.WriteString("}\n\n")
	out.WriteString("func applyRouteOptions(options ...RouteOption) routeOptions {\n")
	out.WriteString("\tvar result routeOptions\n")
	out.WriteString("\tfor _, option := range options {\n")
	out.WriteString("\t\tif option != nil { option(&result) }\n")
	out.WriteString("\t}\n")
	out.WriteString("\treturn result\n")
	out.WriteString("}\n\n")

	fmt.Fprintf(out, "// %s routes generated queries through a pgmesh mesh.\n", opts.ShardedTypeName)
	fmt.Fprintf(out, "type %s[SK any] struct {\n", opts.ShardedTypeName)
	fmt.Fprintf(out, "\tmesh *pgmesh.Mesh[*%s, *%s, SK]\n", opts.ReadTypeName, opts.TypeName)
	fmt.Fprintf(out, "\tresolver %s[SK]\n", opts.ResolverInterfaceName)
	out.WriteString("}\n\n")
	fmt.Fprintf(out, "// %s creates a routed query facade.\n", opts.ShardedConstructor)
	fmt.Fprintf(
		out,
		"func %s[SK any](mesh *pgmesh.Mesh[*%s, *%s, SK], resolver %s[SK]) *%s[SK] {\n",
		opts.ShardedConstructor,
		opts.ReadTypeName,
		opts.TypeName,
		opts.ResolverInterfaceName,
		opts.ShardedTypeName,
	)
	fmt.Fprintf(out, "\treturn &%s[SK]{mesh: mesh, resolver: resolver}\n", opts.ShardedTypeName)
	out.WriteString("}\n\n")

	for index := range queries {
		query := &queries[index]
		if query.route == nil {
			continue
		}
		writeShardedQueryMethod(out, opts, query)
	}
}

func routeOperandsSignature(operands []routeOperand) string {
	parts := make([]string, 0, len(operands))
	for _, operand := range operands {
		parts = append(parts, operand.name+" "+operand.typ)
	}
	return strings.Join(parts, ", ")
}

func writeShardedQueryMethod(out *bytes.Buffer, opts *Options, query *generatedQuery) {
	params := paramsSignature(query.params)
	if params != "" {
		params += ", "
	}
	params += "routeOptions ...RouteOption"
	fmt.Fprintf(out, "// %s executes the generated query on its resolved shard.\n", query.methodName)
	fmt.Fprintf(
		out,
		"func (%s *%s[SK]) %s(%s)%s {\n",
		opts.ReceiverName,
		opts.ShardedTypeName,
		query.methodName,
		params,
		resultsSignature(query.results),
	)
	queryKind := "pgmesh.QueryKindRead"
	if query.kind == queryKindWrite {
		queryKind = "pgmesh.QueryKindWrite"
	}
	fmt.Fprintf(
		out,
		"\tctx, queryTrace := %s.mesh.StartQueryTrace(ctx, %q, %s)\n",
		opts.ReceiverName,
		query.methodName,
		queryKind,
	)
	out.WriteString("\tvar queryErr error\n")
	out.WriteString("\tdefer func() { queryTrace.End(queryErr) }()\n")
	routeArgs := make([]string, 0, len(query.route.operands))
	for _, operand := range query.route.operands {
		routeArgs = append(routeArgs, operand.expression)
	}
	fmt.Fprintf(
		out,
		"\tshardKey := %s.resolver.%s(%s)\n",
		opts.ReceiverName,
		query.route.methodName,
		strings.Join(routeArgs, ", "),
	)
	fmt.Fprintf(out, "\tshard, err := %s.mesh.Shard(shardKey)\n", opts.ReceiverName)
	out.WriteString("\tif err != nil {\n")
	out.WriteString("\t\tqueryErr = err\n")
	writeGeneratedErrorReturn(out, query.results, "err", "\t\t")
	out.WriteString("\t}\n")
	out.WriteString("\toptions := applyRouteOptions(routeOptions...)\n")
	args := callArguments(query.params)
	if query.kind == queryKindRead {
		out.WriteString("\tif options.tx != nil {\n")
		out.WriteString("\t\tqueryTrace.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction, 0)\n")
		writeTracedQueryCall(
			out,
			query,
			fmt.Sprintf("shard.Write().WithTx(options.tx).%s(%s)", query.methodName, args),
			"\t\t",
		)
		out.WriteString("\t}\n")
		out.WriteString("\tif options.primary {\n")
		out.WriteString("\t\tqueryTrace.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary, 0)\n")
		writeTracedQueryCall(
			out,
			query,
			fmt.Sprintf("shard.Write().%s(%s)", query.methodName, args),
			"\t\t",
		)
		out.WriteString("\t}\n")
		out.WriteString("\tqueryTrace.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead, 0)\n")
		writeTracedQueryCall(
			out,
			query,
			fmt.Sprintf("shard.Read().%s(%s)", query.methodName, args),
			"\t",
		)
	} else {
		out.WriteString("\ttarget := shard.Write()\n")
		out.WriteString("\tmode := pgmesh.RouteModePrimary\n")
		out.WriteString("\twriteMirrorCount := shard.WriteMirrorCount()\n")
		out.WriteString("\tif options.tx != nil {\n")
		out.WriteString("\t\ttarget = target.WithTx(options.tx)\n")
		out.WriteString("\t\tmode = pgmesh.RouteModeTransaction\n")
		out.WriteString("\t\twriteMirrorCount = 0\n")
		out.WriteString("\t}\n")
		out.WriteString("\tqueryTrace.SetRoute(shard.VShardIndex(), shard.Name(), mode, writeMirrorCount)\n")
		writeTracedQueryCall(
			out,
			query,
			fmt.Sprintf("target.%s(%s)", query.methodName, args),
			"\t",
		)
	}
	out.WriteString("}\n\n")
}

func writeTracedQueryCall(
	out *bytes.Buffer,
	query *generatedQuery,
	call string,
	indent string,
) {
	if !lastResultIsError(query.results) {
		fmt.Fprintf(out, "%sreturn %s\n", indent, call)
		return
	}

	nonErrorResults := query.results[:len(query.results)-1]
	if len(nonErrorResults) == 0 {
		fmt.Fprintf(out, "%squeryErr = %s\n", indent, call)
		out.WriteString(indent + "return queryErr\n")
		return
	}

	resultVars := resultVariables(len(nonErrorResults))
	for index, result := range nonErrorResults {
		fmt.Fprintf(out, "%svar %s %s\n", indent, resultVars[index], result)
	}
	fmt.Fprintf(
		out,
		"%s%s, queryErr = %s\n",
		indent,
		strings.Join(resultVars, ", "),
		call,
	)
	fmt.Fprintf(out, "%sreturn %s, queryErr\n", indent, strings.Join(resultVars, ", "))
}

func writeGeneratedErrorReturn(out *bytes.Buffer, results []string, errExpression, indent string) {
	nonError := results[:len(results)-1]
	for index, result := range nonError {
		fmt.Fprintf(out, "%svar zero%d %s\n", indent, index, result)
	}
	fmt.Fprint(out, indent+"return ")
	for index := range nonError {
		if index > 0 {
			out.WriteString(", ")
		}
		fmt.Fprintf(out, "zero%d", index)
	}
	if len(nonError) > 0 {
		out.WriteString(", ")
	}
	fmt.Fprintln(out, errExpression)
}

func writeQueryMethods(
	out *bytes.Buffer,
	opts *Options,
	receiverType string,
	queries []generatedQuery,
	kind queryKind,
	mirror bool,
) {
	for idx := range queries {
		query := &queries[idx]
		if query.kind != kind {
			continue
		}
		fmt.Fprintf(out, "// %s executes the generated %s query.\n", query.methodName, query.methodName)
		fmt.Fprintf(out, "func (%s *%s) %s(%s)%s {\n",
			opts.ReceiverName,
			receiverType,
			query.methodName,
			paramsSignature(query.params),
			resultsSignature(query.results),
		)
		writeQueryMethodBody(out, opts, query, mirror)
		out.WriteString("}\n\n")
	}
}

func writeQueryMethodBody(out *bytes.Buffer, opts *Options, query *generatedQuery, mirror bool) {
	args := callArguments(query.params)
	if !lastResultIsError(query.results) {
		fmt.Fprintf(out, "\treturn %s.main.%s(%s)\n", opts.ReceiverName, query.methodName, args)
		return
	}

	nonErrorResults := query.results[:len(query.results)-1]
	if len(nonErrorResults) == 0 {
		fmt.Fprintf(out, "\tif err := %s.main.%s(%s); err != nil {\n", opts.ReceiverName, query.methodName, args)
		out.WriteString("\t\treturn err\n")
		out.WriteString("\t}\n")
		if !mirror {
			out.WriteString("\treturn nil\n")
			return
		}
		if opts.IgnoreMirrorError {
			fmt.Fprintf(
				out,
				"\t_ = %s.mirror(func(%s *%s) error {\n",
				opts.ReceiverName,
				mirrorReceiverName,
				targetName(opts, opts.TargetTypeName),
			)
			fmt.Fprintf(out, "\t\treturn %s.%s(%s)\n", mirrorReceiverName, query.methodName, args)
			out.WriteString("\t})\n")
			out.WriteString("\treturn nil\n")
			return
		}
		fmt.Fprintf(
			out,
			"\treturn %s.mirror(func(%s *%s) error {\n",
			opts.ReceiverName,
			mirrorReceiverName,
			targetName(opts, opts.TargetTypeName),
		)
		fmt.Fprintf(out, "\t\treturn %s.%s(%s)\n", mirrorReceiverName, query.methodName, args)
		out.WriteString("\t})\n")
		return
	}

	resultVars := resultVariables(len(nonErrorResults))
	fmt.Fprintf(out, "\t%s := %s.main.%s(%s)\n",
		strings.Join(appendResultError(resultVars), ", "),
		opts.ReceiverName,
		query.methodName,
		args,
	)
	out.WriteString("\tif err != nil {\n")
	for idx, result := range nonErrorResults {
		fmt.Fprintf(out, "\t\tvar zero%d %s\n", idx, result)
	}
	out.WriteString("\t\treturn ")
	for idx := range nonErrorResults {
		if idx > 0 {
			out.WriteString(", ")
		}
		fmt.Fprintf(out, "zero%d", idx)
	}
	out.WriteString(", err\n")
	out.WriteString("\t}\n")

	if !mirror {
		fmt.Fprintf(out, "\treturn %s, nil\n", strings.Join(resultVars, ", "))
		return
	}
	if opts.IgnoreMirrorError {
		fmt.Fprintf(
			out,
			"\t_ = %s.mirror(func(%s *%s) error {\n",
			opts.ReceiverName,
			mirrorReceiverName,
			targetName(opts, opts.TargetTypeName),
		)
		fmt.Fprintf(out, "\t\t%s := %s.%s(%s)\n",
			strings.Join(discardVariables(len(nonErrorResults)+1), ", "),
			mirrorReceiverName,
			query.methodName,
			args,
		)
		out.WriteString("\t\treturn err\n")
		out.WriteString("\t})\n")
		fmt.Fprintf(out, "\treturn %s, nil\n", strings.Join(resultVars, ", "))
		return
	}

	fmt.Fprintf(
		out,
		"\t%s := %s.mirror(func(%s *%s) error {\n",
		mirrorErrorName,
		opts.ReceiverName,
		mirrorReceiverName,
		targetName(opts, opts.TargetTypeName),
	)
	fmt.Fprintf(out, "\t\t%s := %s.%s(%s)\n",
		strings.Join(discardVariables(len(nonErrorResults)+1), ", "),
		mirrorReceiverName,
		query.methodName,
		args,
	)
	out.WriteString("\t\treturn err\n")
	out.WriteString("\t})\n")
	fmt.Fprintf(out, "\treturn %s, %s\n", strings.Join(resultVars, ", "), mirrorErrorName)
}

func callArguments(params []argument) string {
	args := make([]string, 0, len(params))
	for _, param := range params {
		args = append(args, param.name)
	}
	return strings.Join(args, ", ")
}

func lastResultIsError(results []string) bool {
	return len(results) > 0 && results[len(results)-1] == resultErrorName
}

func resultVariables(count int) []string {
	vars := make([]string, count)
	for idx := range vars {
		vars[idx] = fmt.Sprintf("rv%d", idx)
	}
	return vars
}

func appendResultError(vars []string) []string {
	out := make([]string, 0, len(vars)+1)
	out = append(out, vars...)
	out = append(out, "err")
	return out
}

func discardVariables(count int) []string {
	vars := make([]string, count)
	for idx := range count - 1 {
		vars[idx] = "_"
	}
	vars[count-1] = "err"
	return vars
}

func writeSplitInterface(out *bytes.Buffer, name string, queries []generatedQuery, kind queryKind) {
	fmt.Fprintf(out, "// %s exposes generated %s queries.\n", name, kind)
	fmt.Fprintf(out, "type %s interface {\n", name)
	for _, query := range queries {
		if query.kind != kind {
			continue
		}
		fmt.Fprintf(out, "\t// %s executes the generated %s query.\n", query.methodName, query.methodName)
		fmt.Fprintf(out, "\t%s(%s)%s\n", query.methodName, paramsSignature(query.params), resultsSignature(query.results))
	}
	out.WriteString("}\n\n")
}

func storeTypeName(opts *Options) string {
	if opts.TypeName != "" {
		return opts.TypeName
	}
	return "StoreQueries"
}

func targetName(opts *Options, name string) string {
	if opts.InternalImportPath == "" {
		return name
	}
	return internalQualifier(opts) + "." + name
}

func internalQualifier(opts *Options) string {
	if opts.InternalImportAlias != "" {
		return opts.InternalImportAlias
	}
	return "internal"
}

func importAlias(alias string) string {
	if alias == "" || alias == "internal" {
		return ""
	}
	return alias
}

func privateConstructorName(name string) string {
	if name == "" {
		return ""
	}
	return strings.ToLower(name[:1]) + name[1:]
}

func interfaceName(opts *Options) string {
	if opts.InterfaceName != "" {
		return targetName(opts, opts.InterfaceName)
	}
	return targetName(opts, "Querier")
}

func writeImports(out *bytes.Buffer, imports []importSpec) {
	if len(imports) == 0 {
		return
	}
	out.WriteString("import (\n")
	for _, imp := range imports {
		if imp.name != "" {
			fmt.Fprintf(out, "\t%s %q\n", imp.name, imp.path)
			continue
		}
		fmt.Fprintf(out, "\t%q\n", imp.path)
	}
	out.WriteString(")\n\n")
}

type generatedQuery struct {
	methodName string
	kind       queryKind
	params     []argument
	results    []string
	route      *shardRoute
}

type shardRoute struct {
	name       string
	methodName string
	operands   []routeOperand
}

type routeAnnotation struct {
	name     string
	operands []string
}

type routeOperand struct {
	name       string
	typ        string
	expression string
}

func collectShardRoutes(queries []generatedQuery) ([]shardRoute, error) {
	byName := make(map[string]shardRoute)
	for _, query := range queries {
		if query.route == nil {
			continue
		}
		if previous, ok := byName[query.route.methodName]; ok {
			if previous.name != query.route.name {
				return nil, fmt.Errorf(
					"shard routes %s and %s generate the same resolver method %s",
					previous.name, query.route.name, query.route.methodName,
				)
			}
			if !sameRouteSignature(previous, *query.route) {
				return nil, fmt.Errorf(
					"shard route %s is reused with incompatible parameter types",
					query.route.name,
				)
			}
			continue
		}
		byName[query.route.methodName] = *query.route
	}
	routes := make([]shardRoute, 0, len(byName))
	for _, route := range byName {
		routes = append(routes, route)
	}
	sort.Slice(routes, func(i, j int) bool { return routes[i].methodName < routes[j].methodName })
	return routes, nil
}

func sameRouteSignature(left, right shardRoute) bool {
	if len(left.operands) != len(right.operands) {
		return false
	}
	for index := range left.operands {
		if left.operands[index].typ != right.operands[index].typ {
			return false
		}
	}
	return true
}

type queryKind string

const (
	queryKindRead  queryKind = "read"
	queryKindWrite queryKind = "write"
)

type argument struct {
	name string
	typ  string
}

func paramsSignature(params []argument) string {
	parts := make([]string, 0, len(params))
	for _, param := range params {
		parts = append(parts, param.name+" "+param.typ)
	}
	return strings.Join(parts, ", ")
}

func resultsSignature(results []string) string {
	switch len(results) {
	case 0:
		return ""
	case 1:
		return " " + results[0]
	default:
		return " (" + strings.Join(results, ", ") + ")"
	}
}

type queryValue struct {
	emit        bool           `exhaustruct:"optional"`
	emitPointer bool           `exhaustruct:"optional"`
	name        string         `exhaustruct:"optional"`
	dbName      string         `exhaustruct:"optional"`
	structType  *goStruct      `exhaustruct:"optional"`
	typ         string         `exhaustruct:"optional"`
	column      *plugin.Column `exhaustruct:"optional"`
}

func (v queryValue) isEmpty() bool {
	return v.typ == "" && v.name == "" && v.structType == nil
}

func (v queryValue) defineType(opts *Options) string {
	typ := v.typ
	if typ == "" && v.structType != nil {
		typ = targetName(opts, v.structType.name)
	}
	if v.emitPointer && v.structType != nil {
		return "*" + typ
	}
	return typ
}

func (v queryValue) pairs(opts *Options) []argument {
	if v.isEmpty() {
		return nil
	}
	if !v.emit && v.structType != nil {
		out := make([]argument, 0, len(v.structType.fields))
		for _, field := range v.structType.fields {
			out = append(out, argument{
				name: escape(lowerTitle(field.name)),
				typ:  field.typ,
			})
		}
		return out
	}
	return []argument{{
		name: escape(v.name),
		typ:  v.defineType(opts),
	}}
}

func (v queryValue) slicePair(opts *Options) argument {
	return argument{name: escape(v.name), typ: "[]" + v.defineType(opts)}
}

type goStruct struct {
	table  *plugin.Identifier
	name   string
	fields []goField
}

type goField struct {
	name   string
	dbName string
	typ    string
	column *plugin.Column
}

func buildStructs(req *plugin.GenerateRequest, opts *Options, resolver *typeResolver) []goStruct {
	var structs []goStruct
	for _, schema := range req.GetCatalog().GetSchemas() {
		if skippedSchema(schema.GetName()) {
			continue
		}
		for _, table := range schema.GetTables() {
			tableName := table.GetRel().GetName()
			if schema.GetName() != req.GetCatalog().GetDefaultSchema() {
				tableName = schema.GetName() + "_" + tableName
			}
			if !opts.EmitExactTableNames {
				tableName = singular(tableName)
			}

			strct := goStruct{
				table: &plugin.Identifier{
					Catalog: table.GetRel().GetCatalog(),
					Schema:  schema.GetName(),
					Name:    table.GetRel().GetName(),
				},
				name:   structName(tableName, opts),
				fields: nil,
			}
			for _, column := range table.GetColumns() {
				strct.fields = append(strct.fields, goField{
					name:   structName(column.GetName(), opts),
					dbName: column.GetName(),
					typ:    resolver.goType(column),
					column: column,
				})
			}
			structs = append(structs, strct)
		}
	}
	sort.Slice(structs, func(i, j int) bool {
		return structs[i].name < structs[j].name
	})
	return structs
}

func skippedSchema(name string) bool {
	return name == "pg_catalog" || name == "information_schema"
}

func singular(name string) string {
	switch strings.ToLower(name) {
	case "campus", "meta", "metadata":
		return name
	case "calories":
		return "calorie"
	case "waves":
		return "wave"
	default:
		return inflection.Singular(name)
	}
}

func buildQueries(
	req *plugin.GenerateRequest,
	opts *Options,
	resolver *typeResolver,
	structs []goStruct,
) ([]generatedQuery, error) {
	out := make([]generatedQuery, 0, len(req.GetQueries()))
	for _, query := range req.GetQueries() {
		if query.GetName() == "" || query.GetCmd() == "" {
			continue
		}

		arg, err := buildQueryArg(query, opts, resolver)
		if err != nil {
			return nil, err
		}
		ret, err := buildQueryReturn(req, query, opts, resolver, structs)
		if err != nil {
			return nil, err
		}

		params := []argument{{name: "ctx", typ: "context.Context"}}
		if query.GetCmd() == cmdCopyFrom || strings.HasPrefix(query.GetCmd(), ":batch") {
			if !arg.isEmpty() {
				params = append(params, arg.slicePair(opts))
			}
		} else {
			params = append(params, arg.pairs(opts)...)
		}

		results, err := resultTypes(query, ret, opts)
		if err != nil {
			return nil, err
		}
		for _, result := range results {
			resolver.addImportsForType(result)
		}
		for _, param := range params {
			resolver.addImportsForType(param.typ)
		}

		kind, annotation, err := classifyQuery(query)
		if err != nil {
			return nil, err
		}
		var route *shardRoute
		if annotation != nil {
			if query.GetCmd() == cmdCopyFrom || strings.HasPrefix(query.GetCmd(), ":batch") {
				return nil, fmt.Errorf(
					"query %s uses %s and cannot declare shard metadata; partition the batch and use node-level wrappers",
					query.GetName(), query.GetCmd(),
				)
			}
			route, err = resolveShardRoute(query, arg, annotation, opts)
			if err != nil {
				return nil, err
			}
			if !lastResultIsError(results) {
				return nil, fmt.Errorf("query %s cannot be shard-routed because its generated result has no error", query.GetName())
			}
		}

		out = append(out, generatedQuery{
			methodName: query.GetName(),
			kind:       kind,
			params:     params,
			results:    results,
			route:      route,
		})
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].methodName < out[j].methodName
	})
	return out, nil
}

func classifyQuery(query *plugin.Query) (queryKind, *routeAnnotation, error) {
	if err := validateRawAnnotationOrder(query); err != nil {
		return "", nil, err
	}
	comments := queryComments(query)
	if len(comments) == 0 {
		return "", nil, fmt.Errorf(
			"query %s is missing required kind annotation; add -- kind: read or -- kind: write immediately after -- name",
			query.GetName(),
		)
	}
	kind, err := queryKindFromComment(query.GetName(), comments[0])
	if err != nil {
		return "", nil, err
	}

	var route *routeAnnotation
	if len(comments) > 1 && strings.HasPrefix(strings.ToLower(normalizeComment(comments[1])), "shard:") {
		route, err = parseShardAnnotation(query.GetName(), comments[1])
		if err != nil {
			return "", nil, err
		}
	}
	start := 1
	if route != nil {
		start = 2
	}
	for _, comment := range comments[start:] {
		if strings.HasPrefix(strings.ToLower(normalizeComment(comment)), "shard:") {
			return "", nil, fmt.Errorf(
				"query %s shard annotation must immediately follow its kind annotation",
				query.GetName(),
			)
		}
	}
	return kind, route, nil
}

func validateRawAnnotationOrder(query *plugin.Query) error {
	lines := strings.Split(query.GetText(), "\n")
	nameLine := -1
	for index, rawLine := range lines {
		if strings.HasPrefix(strings.ToLower(strings.TrimSpace(rawLine)), "-- name:") {
			nameLine = index
			break
		}
	}
	if nameLine == -1 {
		return nil
	}
	if nameLine+1 >= len(lines) || !strings.HasPrefix(
		strings.ToLower(normalizeComment(lines[nameLine+1])),
		"kind:",
	) || !strings.HasPrefix(strings.TrimSpace(lines[nameLine+1]), "--") {
		return fmt.Errorf(
			"query %s kind annotation must immediately follow its sqlc name annotation",
			query.GetName(),
		)
	}
	for index := nameLine + 2; index < len(lines); index++ {
		if !strings.HasPrefix(strings.ToLower(normalizeComment(lines[index])), "shard:") {
			continue
		}
		if index != nameLine+2 || !strings.HasPrefix(strings.TrimSpace(lines[index]), "--") {
			return fmt.Errorf(
				"query %s shard annotation must immediately follow its kind annotation",
				query.GetName(),
			)
		}
		break
	}
	return nil
}

func queryComments(query *plugin.Query) []string {
	if comments := query.GetComments(); len(comments) > 0 {
		return comments
	}
	var comments []string
	for rawLine := range strings.SplitSeq(query.GetText(), "\n") {
		line := strings.TrimSpace(rawLine)
		if line == "" || strings.HasPrefix(strings.ToLower(line), "-- name:") {
			continue
		}
		if strings.HasPrefix(line, "--") {
			comments = append(comments, line)
			continue
		}
		break
	}
	return comments
}

func parseShardAnnotation(queryName, comment string) (*routeAnnotation, error) {
	normalized := normalizeComment(comment)
	value := strings.TrimSpace(normalized[len("shard:"):])
	open := strings.IndexByte(value, '(')
	if open <= 0 || !strings.HasSuffix(value, ")") {
		return nil, fmt.Errorf(
			"query %s has malformed shard annotation %q; expected route(parameter, ...)",
			queryName, value,
		)
	}
	name := strings.TrimSpace(value[:open])
	if !validRouteIdentifier(name) {
		return nil, fmt.Errorf("query %s has invalid shard route name %q", queryName, name)
	}
	body := strings.TrimSpace(value[open+1 : len(value)-1])
	if body == "" {
		return &routeAnnotation{name: name, operands: nil}, nil
	}
	parts := strings.Split(body, ",")
	operands := make([]string, 0, len(parts))
	seen := make(map[string]struct{}, len(parts))
	for _, part := range parts {
		operand := strings.TrimSpace(part)
		if !validRouteIdentifier(operand) {
			return nil, fmt.Errorf("query %s has invalid shard operand %q", queryName, operand)
		}
		if _, ok := seen[operand]; ok {
			return nil, fmt.Errorf("query %s repeats shard operand %q", queryName, operand)
		}
		seen[operand] = struct{}{}
		operands = append(operands, operand)
	}
	return &routeAnnotation{name: name, operands: operands}, nil
}

func validRouteIdentifier(value string) bool {
	if value == "" {
		return false
	}
	for index, r := range value {
		if unicode.IsLetter(r) || r == '_' || index > 0 && unicode.IsDigit(r) {
			continue
		}
		return false
	}
	return true
}

func queryKindFromComment(queryName, comment string) (queryKind, error) {
	comment = normalizeComment(comment)
	lower := strings.ToLower(comment)
	if !strings.HasPrefix(lower, "kind:") {
		return "", fmt.Errorf(
			"query %s first comment must be kind annotation; add -- kind: read or -- kind: write before other comments",
			queryName,
		)
	}

	value := strings.TrimSpace(comment[len("kind:"):])
	switch strings.ToLower(value) {
	case string(queryKindRead):
		return queryKindRead, nil
	case string(queryKindWrite):
		return queryKindWrite, nil
	default:
		return "", fmt.Errorf("query %s has invalid kind annotation %q; expected read or write", queryName, value)
	}
}

func normalizeComment(comment string) string {
	comment = strings.TrimSpace(comment)
	comment = strings.TrimPrefix(comment, "--")
	comment = strings.TrimPrefix(comment, "//")
	comment = strings.TrimSpace(comment)
	if strings.HasPrefix(comment, "/*") && strings.HasSuffix(comment, "*/") {
		comment = strings.TrimPrefix(comment, "/*")
		comment = strings.TrimSuffix(comment, "*/")
	}
	return strings.TrimSpace(comment)
}

func buildQueryArg(query *plugin.Query, opts *Options, resolver *typeResolver) (queryValue, error) {
	params := query.GetParams()
	limit := int(*opts.QueryParameterLimit)
	if len(params) == 1 && limit != 0 {
		param := params[0]
		return queryValue{
			name:   escape(paramName(param)),
			dbName: param.GetColumn().GetName(),
			typ:    resolver.goType(param.GetColumn()),
			column: param.GetColumn(),
		}, nil
	}
	if len(params) == 0 {
		return queryValue{}, nil
	}

	columns := make([]goColumn, 0, len(params))
	for _, param := range params {
		columns = append(columns, goColumn{
			id:     int(param.GetNumber()),
			column: param.GetColumn(),
		})
	}
	strct, err := columnsToStruct(query.GetName()+"Params", columns, opts, resolver, false)
	if err != nil {
		return queryValue{}, err
	}
	emit := len(params) > limit || query.GetCmd() == cmdCopyFrom

	return queryValue{
		emit:        emit,
		emitPointer: opts.EmitParamsStructPointers,
		name:        "arg",
		structType:  strct,
	}, nil
}

func resolveShardRoute(
	query *plugin.Query,
	arg queryValue,
	annotation *routeAnnotation,
	opts *Options,
) (*shardRoute, error) {
	route := &shardRoute{
		name:       annotation.name,
		methodName: routeMethodName(annotation.name, opts),
		operands:   make([]routeOperand, 0, len(annotation.operands)),
	}
	if route.methodName == "" {
		return nil, fmt.Errorf("query %s shard route %q does not produce a Go method name", query.GetName(), annotation.name)
	}
	first, _ := utf8.DecodeRuneInString(route.methodName)
	if !validRouteIdentifier(route.methodName) || !unicode.IsUpper(first) {
		return nil, fmt.Errorf(
			"query %s shard route %q generates non-exported or invalid resolver method %q",
			query.GetName(), annotation.name, route.methodName,
		)
	}
	seenNames := make(map[string]struct{}, len(annotation.operands))
	for _, dbName := range annotation.operands {
		operand, ok := routeOperandForArg(arg, dbName, opts)
		if !ok {
			return nil, fmt.Errorf(
				"query %s shard operand %q does not match a SQL parameter",
				query.GetName(), dbName,
			)
		}
		if _, ok := seenNames[operand.name]; ok {
			return nil, fmt.Errorf(
				"query %s shard operands generate duplicate Go parameter %q",
				query.GetName(), operand.name,
			)
		}
		seenNames[operand.name] = struct{}{}
		route.operands = append(route.operands, operand)
	}
	return route, nil
}

func routeMethodName(name string, opts *Options) string {
	if replacement := opts.Rename[name]; replacement != "" {
		return replacement
	}
	parts := splitIdentifier(name)
	for index, part := range parts {
		if strings.EqualFold(part, "p2p") {
			parts[index] = "P2P"
			continue
		}
		parts[index] = structName(part, opts)
	}
	return strings.Join(parts, "")
}

func routeOperandForArg(arg queryValue, dbName string, opts *Options) (routeOperand, bool) {
	if arg.structType != nil {
		for _, field := range arg.structType.fields {
			if field.dbName != dbName {
				continue
			}
			expression := escape(lowerTitle(field.name))
			if arg.emit {
				expression = escape(arg.name) + "." + field.name
			}
			return routeOperand{
				name:       escape(lowerTitle(structName(dbName, opts))),
				typ:        field.typ,
				expression: expression,
			}, true
		}
		return routeOperand{name: "", typ: "", expression: ""}, false
	}
	if arg.dbName != dbName {
		return routeOperand{name: "", typ: "", expression: ""}, false
	}
	return routeOperand{
		name:       escape(lowerTitle(structName(dbName, opts))),
		typ:        arg.typ,
		expression: escape(arg.name),
	}, true
}

func buildQueryReturn(
	req *plugin.GenerateRequest,
	query *plugin.Query,
	opts *Options,
	resolver *typeResolver,
	structs []goStruct,
) (queryValue, error) {
	if !queryReturnsData(query.GetCmd()) {
		return queryValue{}, nil
	}
	columns := query.GetColumns()
	if len(columns) == 1 && columns[0].GetEmbedTable() == nil {
		column := columns[0]
		name := strings.ReplaceAll(columnName(column, 0), "$", "_")
		return queryValue{
			name:   escape(name),
			dbName: name,
			typ:    resolver.goType(column),
			column: column,
		}, nil
	}
	if len(columns) == 0 {
		return queryValue{}, nil
	}

	var model *goStruct
	for idx := range structs {
		strct := &structs[idx]
		if queryColumnsMatchStruct(req, opts, resolver, columns, strct) {
			model = strct
			break
		}
	}

	emit := false
	if model == nil {
		goColumns := make([]goColumn, 0, len(columns))
		for idx, column := range columns {
			goColumns = append(goColumns, goColumn{
				id:     idx,
				column: column,
			})
		}
		var err error
		model, err = columnsToStruct(query.GetName()+"Row", goColumns, opts, resolver, true)
		if err != nil {
			return queryValue{}, err
		}
		emit = true
	}
	return queryValue{
		emit:        emit,
		emitPointer: opts.EmitResultStructPointers,
		name:        "i",
		structType:  model,
	}, nil
}

func queryReturnsData(cmd string) bool {
	switch cmd {
	case ":one", ":many", ":batchone", ":batchmany":
		return true
	default:
		return false
	}
}

func resultTypes(query *plugin.Query, ret queryValue, opts *Options) ([]string, error) {
	switch query.GetCmd() {
	case ":one":
		return []string{ret.defineType(opts), resultErrorName}, nil
	case ":many":
		return []string{"[]" + ret.defineType(opts), resultErrorName}, nil
	case ":exec":
		return []string{resultErrorName}, nil
	case ":execrows", cmdCopyFrom:
		return []string{"int64", resultErrorName}, nil
	case ":execresult":
		return []string{"pgconn.CommandTag", resultErrorName}, nil
	case ":batchexec", ":batchone", ":batchmany":
		return []string{"*" + targetName(opts, query.GetName()+"BatchResults")}, nil
	default:
		return nil, fmt.Errorf("unsupported query command %q for %s", query.GetCmd(), query.GetName())
	}
}

func queryColumnsMatchStruct(
	req *plugin.GenerateRequest,
	opts *Options,
	resolver *typeResolver,
	columns []*plugin.Column,
	strct *goStruct,
) bool {
	if len(strct.fields) != len(columns) {
		return false
	}
	for idx, field := range strct.fields {
		column := columns[idx]
		if field.name != structName(columnName(column, idx), opts) {
			return false
		}
		if field.typ != resolver.goType(column) {
			return false
		}
		if !sameTableName(column.GetTable(), strct.table, req.GetCatalog().GetDefaultSchema()) {
			return false
		}
	}
	return true
}

type goColumn struct {
	id     int
	column *plugin.Column
}

func columnsToStruct(
	name string,
	columns []goColumn,
	opts *Options,
	resolver *typeResolver,
	useID bool,
) (*goStruct, error) {
	strct := &goStruct{
		table:  nil,
		name:   name,
		fields: nil,
	}
	seen := map[string][]int{}
	suffixes := map[int]int{}
	for idx, column := range columns {
		columnName := columnName(column.column, idx)
		fieldName := structName(columnName, opts)
		baseFieldName := fieldName

		suffix := 0
		if existing, ok := suffixes[column.id]; ok && useID {
			suffix = existing
		} else if count := len(seen[fieldName]); count > 0 && !column.column.GetIsNamedParam() {
			suffix = count + 1
		}
		suffixes[column.id] = suffix
		if suffix > 0 {
			fieldName = fmt.Sprintf("%s_%d", fieldName, suffix)
		}

		strct.fields = append(strct.fields, goField{
			name:   fieldName,
			dbName: columnName,
			typ:    resolver.goType(column.column),
			column: column.column,
		})
		seen[baseFieldName] = append(seen[baseFieldName], idx)
	}
	return strct, checkIncompatibleFieldTypes(strct.fields)
}

func checkIncompatibleFieldTypes(fields []goField) error {
	fieldTypes := map[string]string{}
	for _, field := range fields {
		if existing, ok := fieldTypes[field.name]; ok && existing != field.typ {
			return fmt.Errorf("named param %s has incompatible types: %s, %s", field.name, existing, field.typ)
		}
		fieldTypes[field.name] = field.typ
	}
	return nil
}

func columnName(column *plugin.Column, pos int) string {
	if column.GetName() != "" {
		return column.GetName()
	}
	return fmt.Sprintf("column_%d", pos+1)
}

func paramName(param *plugin.Parameter) string {
	if param.GetColumn().GetName() != "" {
		return argName(param.GetColumn().GetName())
	}
	return fmt.Sprintf("dollar_%d", param.GetNumber())
}

func argName(name string) string {
	var out strings.Builder
	for idx, part := range strings.Split(name, "_") {
		switch {
		case idx == 0:
			out.WriteString(strings.ToLower(part))
		case strings.EqualFold(part, "id"):
			out.WriteString("ID")
		default:
			out.WriteString(title(part))
		}
	}
	return out.String()
}

func structName(name string, opts *Options) string {
	if replacement := opts.Rename[name]; replacement != "" {
		return replacement
	}
	parts := splitIdentifier(name)
	for idx, part := range parts {
		lower := strings.ToLower(part)
		if strings.EqualFold(lower, "id") {
			parts[idx] = "ID"
			continue
		}
		parts[idx] = title(lower)
	}
	result := strings.Join(parts, "")
	first, _ := utf8.DecodeRuneInString(result)
	if unicode.IsDigit(first) {
		return "_" + result
	}
	return result
}

func splitIdentifier(name string) []string {
	var parts []string
	var current strings.Builder
	for _, r := range name {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			current.WriteRune(r)
			continue
		}
		if current.Len() > 0 {
			parts = append(parts, current.String())
			current.Reset()
		}
	}
	if current.Len() > 0 {
		parts = append(parts, current.String())
	}
	return parts
}

func title(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func lowerTitle(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func escape(name string) string {
	if goKeywords[name] {
		return name + "_"
	}
	return name
}

var goKeywords = map[string]bool{
	"break":       true,
	"default":     true,
	"func":        true,
	"interface":   true,
	"select":      true,
	"case":        true,
	"defer":       true,
	"go":          true,
	"map":         true,
	"struct":      true,
	"chan":        true,
	"else":        true,
	"goto":        true,
	"package":     true,
	"switch":      true,
	"const":       true,
	"fallthrough": true,
	"if":          true,
	"range":       true,
	"type":        true,
	"continue":    true,
	"for":         true,
	"import":      true,
	"return":      true,
	"var":         true,
}

func sameTableName(left, right *plugin.Identifier, defaultSchema string) bool {
	if left == nil || right == nil {
		return false
	}
	leftSchema := left.GetSchema()
	if leftSchema == "" {
		leftSchema = defaultSchema
	}
	rightSchema := right.GetSchema()
	if rightSchema == "" {
		rightSchema = defaultSchema
	}
	return left.GetCatalog() == right.GetCatalog() &&
		leftSchema == rightSchema &&
		left.GetName() == right.GetName()
}

func (r *typeResolver) goType(column *plugin.Column) string {
	for idx := range r.opts.Overrides {
		override := &r.opts.Overrides[idx]
		if override.Column == "" || !override.matchesColumn(column, r.req.GetCatalog().GetDefaultSchema()) {
			continue
		}
		typ := r.overrideType(override)
		if column.GetIsSqlcSlice() {
			return "[]" + typ
		}
		return typ
	}
	for idx := range r.opts.Overrides {
		override := &r.opts.Overrides[idx]
		if !override.matchesColumn(column, r.req.GetCatalog().GetDefaultSchema()) {
			continue
		}
		typ := r.overrideType(override)
		if column.GetIsSqlcSlice() {
			typ = "[]" + typ
		} else if column.GetIsArray() {
			typ = strings.Repeat("[]", int(column.GetArrayDims())) + typ
		}
		return typ
	}

	typ := r.goInnerType(column)
	if column.GetIsSqlcSlice() {
		typ = "[]" + typ
	} else if column.GetIsArray() {
		typ = strings.Repeat("[]", int(column.GetArrayDims())) + typ
	}
	return typ
}

func (r *typeResolver) overrideType(override *override) string {
	typ := override.typeName
	if r.opts.InternalImportPath == "" || override.importPath != "" || typeQualifier(typ) != "" {
		return typ
	}
	prefixLength := 0
	for strings.HasPrefix(typ[prefixLength:], "[]") || strings.HasPrefix(typ[prefixLength:], "*") {
		if strings.HasPrefix(typ[prefixLength:], "[]") {
			prefixLength += 2
			continue
		}
		prefixLength++
	}
	base := typ[prefixLength:]
	if base == "interface{}" || types.Universe.Lookup(base) != nil {
		return typ
	}
	return typ[:prefixLength] + targetName(r.opts, base)
}

func (r *typeResolver) addImportsForType(typ string) {
	r.imports.addForType(typ)
	for idx := range r.opts.Overrides {
		override := &r.opts.Overrides[idx]
		if override.importPath == "" {
			continue
		}
		qualifier := typeQualifier(override.typeName)
		if qualifier == "" || !typeUsesQualifier(typ, qualifier) {
			continue
		}
		r.imports.addNamed(override.importAlias, override.importPath)
	}
}

func typeQualifier(typ string) string {
	typ = strings.TrimPrefix(typ, "[]")
	typ = strings.TrimPrefix(typ, "*")
	before, _, ok := strings.Cut(typ, ".")
	if !ok {
		return ""
	}
	return before
}

func (r *typeResolver) goInnerType(column *plugin.Column) string {
	switch r.req.GetSettings().GetEngine() {
	case "postgresql":
		return r.postgresType(column)
	default:
		return emptyInterfaceType
	}
}

func (r *typeResolver) postgresType(column *plugin.Column) string {
	columnType := dataType(column.GetType())
	notNull := column.GetNotNull() || column.GetIsArray()
	driver := sqlDriver(r.opts.SQLPackage)
	emitPointersForNull := driver.isPGX() && r.opts.EmitPointersForNullTypes
	emitPointersForNullEnums := emitPointersForNull
	if r.opts.EmitPointersForNullEnumType != nil {
		emitPointersForNullEnums = driver.isPGX() && *r.opts.EmitPointersForNullEnumType
	}

	switch columnType {
	case "serial", "serial4", "pg_catalog.serial4", "integer", "int", "int4", "pg_catalog.int4":
		return nullableType("int32", "*int32", "pgtype.Int4", "sql.NullInt32", notNull, emitPointersForNull, driver)
	case "bigserial", "serial8", "pg_catalog.serial8", "bigint", "int8", "pg_catalog.int8":
		return nullableType("int64", "*int64", "pgtype.Int8", "sql.NullInt64", notNull, emitPointersForNull, driver)
	case "smallserial", "serial2", "pg_catalog.serial2", "smallint", "int2", "pg_catalog.int2":
		return nullableType("int16", "*int16", "pgtype.Int2", "sql.NullInt16", notNull, emitPointersForNull, driver)
	case "float", "double precision", "float8", "pg_catalog.float8":
		return nullableType("float64", "*float64", "pgtype.Float8", "sql.NullFloat64", notNull, emitPointersForNull, driver)
	case "real", "float4", "pg_catalog.float4":
		return nullableType("float32", "*float32", "pgtype.Float4", "sql.NullFloat64", notNull, emitPointersForNull, driver)
	case "boolean", "bool", "pg_catalog.bool":
		return nullableType("bool", "*bool", "pgtype.Bool", "sql.NullBool", notNull, emitPointersForNull, driver)
	case "text", "pg_catalog.varchar", "pg_catalog.bpchar", "varchar", "string", "citext", "name":
		return nullableType("string", "*string", "pgtype.Text", "sql.NullString", notNull, emitPointersForNull, driver)
	case "bytea", "blob", "pg_catalog.bytea":
		return "[]byte"
	case "json", "pg_catalog.json", "jsonb", "pg_catalog.jsonb":
		if driver == sqlDriverPGXV5 {
			return "[]byte"
		}
		if notNull {
			return "json.RawMessage"
		}
		return "pqtype.NullRawMessage"
	case "date":
		if driver == sqlDriverPGXV5 {
			return "pgtype.Date"
		}
		return nullableStdlibType("time.Time", "*time.Time", "sql.NullTime", notNull, emitPointersForNull)
	case "pg_catalog.time":
		if driver == sqlDriverPGXV5 {
			return "pgtype.Time"
		}
		return nullableStdlibType("time.Time", "*time.Time", "sql.NullTime", notNull, emitPointersForNull)
	case "pg_catalog.timetz":
		return nullableStdlibType("time.Time", "*time.Time", "sql.NullTime", notNull, emitPointersForNull)
	case "pg_catalog.timestamp", "timestamp":
		if driver == sqlDriverPGXV5 {
			return "pgtype.Timestamp"
		}
		return nullableStdlibType("time.Time", "*time.Time", "sql.NullTime", notNull, emitPointersForNull)
	case "pg_catalog.timestamptz", "timestamptz":
		if driver == sqlDriverPGXV5 {
			return "pgtype.Timestamptz"
		}
		return nullableStdlibType("time.Time", "*time.Time", "sql.NullTime", notNull, emitPointersForNull)
	case "uuid":
		if driver == sqlDriverPGXV5 {
			return "pgtype.UUID"
		}
		return nullableStdlibType("uuid.UUID", "*uuid.UUID", "uuid.NullUUID", notNull, emitPointersForNull)
	case "numeric", "pg_catalog.numeric", "money":
		if driver.isPGX() {
			return "pgtype.Numeric"
		}
		return nullableStdlibType("string", "*string", "sql.NullString", notNull, emitPointersForNull)
	case "inet":
		if notNull {
			return "netip.Addr"
		}
		return "*netip.Addr"
	case "cidr":
		if notNull {
			return "netip.Prefix"
		}
		return "*netip.Prefix"
	case "macaddr", "macaddr8":
		return "net.HardwareAddr"
	case "ltree", "lquery", "ltxtquery":
		return nullableType("string", "*string", "pgtype.Text", "sql.NullString", notNull, emitPointersForNull, driver)
	case "interval", "pg_catalog.interval":
		return "pgtype.Interval"
	case "daterange":
		return "pgtype.Range[pgtype.Date]"
	case "datemultirange":
		return "pgtype.Multirange[pgtype.Range[pgtype.Date]]"
	case "tsrange":
		return "pgtype.Range[pgtype.Timestamp]"
	case "tsmultirange":
		return "pgtype.Multirange[pgtype.Range[pgtype.Timestamp]]"
	case "tstzrange":
		return "pgtype.Range[pgtype.Timestamptz]"
	case "tstzmultirange":
		return "pgtype.Multirange[pgtype.Range[pgtype.Timestamptz]]"
	case "numrange":
		return "pgtype.Range[pgtype.Numeric]"
	case "nummultirange":
		return "pgtype.Multirange[pgtype.Range[pgtype.Numeric]]"
	case "int4range":
		return "pgtype.Range[pgtype.Int4]"
	case "int4multirange":
		return "pgtype.Multirange[pgtype.Range[pgtype.Int4]]"
	case "int8range":
		return "pgtype.Range[pgtype.Int8]"
	case "int8multirange":
		return "pgtype.Multirange[pgtype.Range[pgtype.Int8]]"
	case "hstore":
		return "pgtype.Hstore"
	case "bit", "varbit", "pg_catalog.bit", "pg_catalog.varbit":
		return "pgtype.Bits"
	case "cid", "oid":
		return "pgtype.Uint32"
	case "tid":
		return "pgtype.TID"
	case "xid":
		return "pgtype.Uint32"
	case "xid8":
		return "pgtype.Uint64"
	case "box":
		return "pgtype.Box"
	case "circle":
		return "pgtype.Circle"
	case "line":
		return "pgtype.Line"
	case "lseg":
		return "pgtype.Lseg"
	case "path":
		return "pgtype.Path"
	case "point":
		return "pgtype.Point"
	case "polygon":
		return "pgtype.Polygon"
	case "vector":
		if emitPointersForNull {
			return "*pgvector.Vector"
		}
		return "pgvector.Vector"
	case "void", "any":
		return emptyInterfaceType
	default:
		return r.customPostgresType(columnType, notNull, emitPointersForNull, emitPointersForNullEnums)
	}
}

func (r *typeResolver) customPostgresType(
	columnType string,
	notNull bool,
	emitPointersForNull bool,
	emitPointersForNullEnums bool,
) string {
	parts := strings.Split(columnType, ".")
	var schemaName, typeName string
	switch len(parts) {
	case 1:
		schemaName = r.req.GetCatalog().GetDefaultSchema()
		typeName = parts[0]
	case 2:
		schemaName = parts[0]
		typeName = parts[1]
	case 3:
		schemaName = parts[1]
		typeName = parts[2]
	default:
		return emptyInterfaceType
	}

	for _, schema := range r.req.GetCatalog().GetSchemas() {
		if schema.GetName() != schemaName || skippedSchema(schema.GetName()) {
			continue
		}
		for _, enum := range schema.GetEnums() {
			if enum.GetName() != typeName {
				continue
			}
			name := enum.GetName()
			if schemaName != r.req.GetCatalog().GetDefaultSchema() {
				name = schemaName + "_" + name
			}
			name = structName(name, r.opts)
			if notNull {
				return targetName(r.opts, name)
			}
			if emitPointersForNullEnums {
				return "*" + targetName(r.opts, name)
			}
			return targetName(r.opts, "Null"+name)
		}
		for _, composite := range schema.GetCompositeTypes() {
			if composite.GetName() != typeName {
				continue
			}
			return nullableStdlibType("string", "*string", "sql.NullString", notNull, emitPointersForNull)
		}
	}
	return emptyInterfaceType
}

func nullableType(
	notNullType string,
	pointerType string,
	pgxType string,
	sqlNullType string,
	notNull bool,
	emitPointersForNull bool,
	driver sqlDriver,
) string {
	if notNull {
		return notNullType
	}
	if emitPointersForNull {
		return pointerType
	}
	if driver == sqlDriverPGXV5 {
		return pgxType
	}
	return sqlNullType
}

func nullableStdlibType(notNullType, pointerType, nullType string, notNull, emitPointersForNull bool) string {
	if notNull {
		return notNullType
	}
	if emitPointersForNull {
		return pointerType
	}
	return nullType
}

type sqlDriver string

const (
	sqlDriverLibPQ sqlDriver = "database/sql"
	sqlDriverPGXV4 sqlDriver = "pgx/v4"
	sqlDriverPGXV5 sqlDriver = "pgx/v5"
)

func (d sqlDriver) isPGX() bool {
	return d == sqlDriverPGXV4 || d == sqlDriverPGXV5
}

type override struct {
	GoType                 goType `json:"go_type"`
	DBType                 string `json:"db_type"`
	DeprecatedPostgresType string `json:"postgres_type"`
	Nullable               bool   `json:"nullable"`
	DeprecatedNull         bool   `json:"null"`
	Unsigned               bool   `json:"unsigned"`
	Column                 string `json:"column"`

	typeName     string
	importPath   string
	importAlias  string
	columnName   string
	tableCatalog string
	tableSchema  string
	tableName    string
}

func (o *override) parse(req *plugin.GenerateRequest) error {
	if o.DeprecatedPostgresType != "" && o.DBType == "" {
		o.DBType = o.DeprecatedPostgresType
	}
	if o.DeprecatedNull {
		o.Nullable = true
	}
	if o.DBType == "" && o.Column == "" {
		return errors.New("override must specify db_type or column")
	}
	if o.DBType != "" && o.Column != "" {
		return errors.New("override cannot specify both db_type and column")
	}
	parsed, err := o.GoType.parse()
	if err != nil {
		return err
	}
	o.typeName = parsed.typeName
	o.importPath = parsed.importPath
	o.importAlias = parsed.importAlias
	if o.Column != "" {
		if err := o.parseColumn(req); err != nil {
			return err
		}
	}
	return nil
}

func (o *override) parseColumn(req *plugin.GenerateRequest) error {
	parts := strings.Split(o.Column, ".")
	defaultSchema := req.GetCatalog().GetDefaultSchema()
	if defaultSchema == "" {
		defaultSchema = "public"
	}
	switch len(parts) {
	case 2:
		o.tableSchema = defaultSchema
		o.tableName = parts[0]
		o.columnName = parts[1]
	case 3:
		o.tableSchema = parts[0]
		o.tableName = parts[1]
		o.columnName = parts[2]
	case 4:
		o.tableCatalog = parts[0]
		o.tableSchema = parts[1]
		o.tableName = parts[2]
		o.columnName = parts[3]
	default:
		return fmt.Errorf("invalid column override %q", o.Column)
	}
	for _, pattern := range []string{o.tableCatalog, o.tableSchema, o.tableName, o.columnName} {
		if pattern == "" {
			continue
		}
		if _, err := compileMatchPattern(pattern); err != nil {
			return fmt.Errorf("invalid column override %q: %w", o.Column, err)
		}
	}
	return nil
}

func (o *override) matchesColumn(column *plugin.Column, defaultSchema string) bool {
	if o.DBType != "" {
		columnType := dataType(column.GetType())
		notNull := column.GetNotNull() || column.GetIsArray()
		return dbTypesEqual(o.DBType, columnType, defaultSchema) &&
			o.Nullable != notNull &&
			o.Unsigned == column.GetUnsigned()
	}
	if o.Column == "" {
		return false
	}
	table := column.GetTable()
	if table == nil {
		return false
	}
	schema := table.GetSchema()
	if schema == "" {
		schema = defaultSchema
	}
	name := column.GetName()
	if column.GetOriginalName() != "" {
		name = column.GetOriginalName()
	}
	if o.tableCatalog != "" && !matchPattern(o.tableCatalog, table.GetCatalog()) {
		return false
	}
	return matchPattern(o.tableSchema, schema) &&
		matchPattern(o.tableName, table.GetName()) &&
		matchPattern(o.columnName, name)
}

func matchPattern(pattern, value string) bool {
	compiled, err := compileMatchPattern(pattern)
	return err == nil && compiled.MatchString(value)
}

func compileMatchPattern(pattern string) (*regexp.Regexp, error) {
	var expression strings.Builder
	escaped := false
	for _, char := range pattern {
		if escaped {
			escaped = false
			switch char {
			case '*', '?', '\\':
				expression.WriteRune('\\')
				expression.WriteRune(char)
			default:
				return nil, fmt.Errorf("invalid escaped character %q", char)
			}
			continue
		}
		switch char {
		case '\\':
			escaped = true
		case '*':
			expression.WriteString(".*")
		case '?':
			expression.WriteRune('.')
		default:
			expression.WriteString(regexp.QuoteMeta(string(char)))
		}
	}
	if escaped {
		return nil, errors.New("unterminated escape at end of pattern")
	}
	return regexp.Compile("^" + expression.String() + "$")
}

func dbTypesEqual(configured, actual, defaultSchema string) bool {
	if configured == actual {
		return true
	}
	if !strings.Contains(actual, ".") && defaultSchema != "" && configured == defaultSchema+"."+actual {
		return true
	}
	return false
}

type goType struct {
	path    string
	pkg     string
	name    string
	pointer bool
	slice   bool
	spec    string
}

func (g *goType) UnmarshalJSON(data []byte) error {
	var spec string
	if err := json.Unmarshal(data, &spec); err == nil {
		g.spec = spec
		return nil
	}
	var raw struct {
		Path    string `json:"import"`
		Package string `json:"package"`
		Name    string `json:"type"`
		Pointer bool   `json:"pointer"`
		Slice   bool   `json:"slice"`
	}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	g.path = raw.Path
	g.pkg = raw.Package
	g.name = raw.Name
	g.pointer = raw.Pointer
	g.slice = raw.Slice
	return nil
}

type parsedGoType struct {
	typeName    string
	importPath  string
	importAlias string
}

func (g goType) parse() (parsedGoType, error) {
	if g.spec != "" {
		return parseGoTypeSpec(g.spec)
	}
	if g.path == "" && g.pkg != "" {
		return parsedGoType{}, errors.New("go_type package requires an import path")
	}

	typeName := g.name
	pkg := g.pkg
	alias := ""
	if pkg == "" && g.path != "" {
		pkg = packageNameForImport(g.path)
	}
	if pkg != "" {
		typeName = pkg + "." + typeName
		if g.pkg != "" && g.pkg != packageNameForImport(g.path) {
			alias = g.pkg
		}
	}
	if g.pointer {
		typeName = "*" + typeName
	}
	if g.slice {
		typeName = "[]" + typeName
	}
	return parsedGoType{typeName: typeName, importPath: g.path, importAlias: alias}, nil
}

func parseGoTypeSpec(spec string) (parsedGoType, error) {
	lastDot := strings.LastIndex(spec, ".")
	lastSlash := strings.LastIndex(spec, "/")
	if lastDot == -1 && lastSlash == -1 {
		for _, basic := range types.Typ {
			if basic != nil && basic.Info() != 0 && basic.Info()&types.IsUntyped == 0 && basic.Name() == spec {
				return parsedGoType{typeName: spec, importPath: "", importAlias: ""}, nil
			}
		}
		return parsedGoType{}, fmt.Errorf("go_type specifier %q is not a Go basic type", spec)
	}
	if lastDot == -1 {
		return parsedGoType{}, fmt.Errorf("go_type specifier %q must use package.type format", spec)
	}
	typeName := spec[lastSlash+1:]
	typeName = strings.TrimPrefix(typeName, "go-")
	typeName = strings.TrimSuffix(typeName, "-go")
	importPath := spec[:lastDot]
	if strings.HasPrefix(spec, "*") {
		importPath = strings.TrimPrefix(importPath, "*")
		typeName = "*" + strings.TrimPrefix(typeName, "*")
	}
	return parsedGoType{
		typeName:    typeName,
		importPath:  importPath,
		importAlias: "",
	}, nil
}

func packageNameForImport(path string) string {
	base := filepath.Base(path)
	base = strings.TrimPrefix(base, "go-")
	base = strings.TrimSuffix(base, "-go")
	if strings.HasPrefix(base, "v") && len(base) > 1 && isDigits(base[1:]) {
		parent := filepath.Base(filepath.Dir(path))
		parent = strings.TrimPrefix(parent, "go-")
		parent = strings.TrimSuffix(parent, "-go")
		return strings.Map(importPackageRune, parent)
	}
	return strings.Map(importPackageRune, base)
}

func importPackageRune(r rune) rune {
	if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_' {
		return unicode.ToLower(r)
	}
	return '_'
}

func isDigits(s string) bool {
	for _, r := range s {
		if !unicode.IsDigit(r) {
			return false
		}
	}
	return s != ""
}

func dataType(identifier *plugin.Identifier) string {
	if identifier == nil {
		return ""
	}
	if identifier.GetSchema() != "" {
		return identifier.GetSchema() + "." + identifier.GetName()
	}
	return identifier.GetName()
}
