// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings_queries.sql

package one

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT key, value
FROM application_settings
WHERE key = $1
`

// kind: read
// store: Settings
func (q *Queries) GetSetting(ctx context.Context, key string) (*ApplicationSetting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i ApplicationSetting
	err := row.Scan(&i.Key, &i.Value)
	return &i, err
}

const upsertSetting = `-- name: UpsertSetting :one
INSERT INTO application_settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value
RETURNING key, value
`

type UpsertSettingParams struct {
	Key   string
	Value string
}

// kind: write
// store: Settings
func (q *Queries) UpsertSetting(ctx context.Context, arg *UpsertSettingParams) (*ApplicationSetting, error) {
	row := q.db.QueryRow(ctx, upsertSetting, arg.Key, arg.Value)
	var i ApplicationSetting
	err := row.Scan(&i.Key, &i.Value)
	return &i, err
}
