// Code generated by pgmesh. DO NOT EDIT.

package one

import (
	"context"
	"github.com/jackc/pgx/v5"
)

// readQueries exposes read-only generated queries.
type readQueries struct {
	main *Queries
}

func newReadQueries(q *Queries) *readQueries {
	return &readQueries{main: q}
}

// WithTx returns a read wrapper that executes queries through tx.
func (q *readQueries) WithTx(tx pgx.Tx) *readQueries {
	return newReadQueries(q.main.WithTx(tx))
}

// GetSetting executes the generated GetSetting query.
func (q *readQueries) GetSetting(ctx context.Context, key string) (*ApplicationSetting, error) {
	rv0, err := q.main.GetSetting(ctx, key)
	if err != nil {
		var zero0 *ApplicationSetting
		return zero0, err
	}
	return rv0, nil
}
