// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package one

import (
	"context"
)

type Querier interface {
	// kind: read
	// store: Settings
	GetSetting(ctx context.Context, key string) (*ApplicationSetting, error)
	// kind: write
	// store: Settings
	UpsertSetting(ctx context.Context, arg *UpsertSettingParams) (*ApplicationSetting, error)
}

var _ Querier = (*Queries)(nil)
