// Code generated by pgmesh. DO NOT EDIT.

package one

import (
	"context"
)

// readQuerier exposes generated read queries.
type readQuerier interface {
	// GetSetting executes the generated GetSetting query.
	GetSetting(ctx context.Context, key string) (*ApplicationSetting, error)
}

// writeQuerier exposes generated write queries.
type writeQuerier interface {
	// UpsertSetting executes the generated UpsertSetting query.
	UpsertSetting(ctx context.Context, arg *UpsertSettingParams) (*ApplicationSetting, error)
}

// Store is the topology-independent generated query API.
type Store interface {
	// GetSetting executes the generated GetSetting query.
	GetSetting(ctx context.Context, key string, storeOptions ...QueryOption) (*ApplicationSetting, error)
	// UpsertSetting executes the generated UpsertSetting query.
	UpsertSetting(ctx context.Context, arg *UpsertSettingParams, storeOptions ...QueryOption) (*ApplicationSetting, error)
}

var _ readQuerier = (*readQueries)(nil)
var _ writeQuerier = (*writeQueries)(nil)
var _ Querier = (*queryStore)(nil)
