// Code generated by pgmesh. DO NOT EDIT.

package store

import (
	"context"
	db "github.com/clnv/pgmesh/integration/fixture/separate/internal"
	"github.com/jackc/pgx/v5"
)

// readQueries exposes read-only generated queries.
type readQueries struct {
	main *db.Queries
}

func newReadQueries(q *db.Queries) *readQueries {
	return &readQueries{main: q}
}

// WithTx returns a read wrapper that executes queries through tx.
func (q *readQueries) WithTx(tx pgx.Tx) *readQueries {
	return newReadQueries(q.main.WithTx(tx))
}

// GetAnalysis executes the generated GetAnalysis query.
func (q *readQueries) GetAnalysis(ctx context.Context, arg *db.GetAnalysisParams) (*db.Analysis, error) {
	rv0, err := q.main.GetAnalysis(ctx, arg)
	if err != nil {
		var zero0 *db.Analysis
		return zero0, err
	}
	return rv0, nil
}

// GetUser executes the generated GetUser query.
func (q *readQueries) GetUser(ctx context.Context, arg *db.GetUserParams) (*db.User, error) {
	rv0, err := q.main.GetUser(ctx, arg)
	if err != nil {
		var zero0 *db.User
		return zero0, err
	}
	return rv0, nil
}
