// Code generated by pgmesh. DO NOT EDIT.

package store

import (
	"context"
	"database/sql"
	"errors"
	pgmesh "github.com/clnv/pgmesh"
	db "github.com/clnv/pgmesh/integration/fixture/separate/internal"
	"github.com/jackc/pgx/v5"
)

// ReadQuerier exposes generated read queries.
type ReadQuerier interface {
	// GetAnalysis executes the generated GetAnalysis query.
	GetAnalysis(ctx context.Context, arg *db.GetAnalysisParams) (*db.Analysis, error)
	// GetUser executes the generated GetUser query.
	GetUser(ctx context.Context, arg *db.GetUserParams) (*db.User, error)
	// ListUsers executes the generated ListUsers query.
	ListUsers(ctx context.Context) ([]*db.User, error)
}

// WriteQuerier exposes generated write queries.
type WriteQuerier interface {
	// CopyUsers executes the generated CopyUsers query.
	CopyUsers(ctx context.Context, arg []*db.CopyUsersParams) (int64, error)
	// CreateUser executes the generated CreateUser query.
	CreateUser(ctx context.Context, arg *db.CreateUserParams) (*db.User, error)
}

// StoreQuerier combines the generated read and write query interfaces.
type StoreQuerier interface {
	ReadQuerier
	WriteQuerier
}

var _ ReadQuerier = (*ReadQueries)(nil)
var _ WriteQuerier = (*WriteQueries)(nil)
var _ StoreQuerier = (*StoreQueries)(nil)
var _ db.Querier = (*StoreQueries)(nil)

// ReadQueries exposes read-only generated queries.
type ReadQueries struct {
	main *db.Queries
}

// NewReadQueries creates a read-only query wrapper.
func NewReadQueries(database db.DBTX) *ReadQueries {
	return newReadQueries(db.New(database))
}

func newReadQueries(q *db.Queries) *ReadQueries {
	return &ReadQueries{main: q}
}

// WithTx returns a read wrapper that executes queries through tx.
func (q *ReadQueries) WithTx(tx pgx.Tx) *ReadQueries {
	return newReadQueries(q.main.WithTx(tx))
}

// GetAnalysis executes the generated GetAnalysis query.
func (q *ReadQueries) GetAnalysis(ctx context.Context, arg *db.GetAnalysisParams) (*db.Analysis, error) {
	rv0, err := q.main.GetAnalysis(ctx, arg)
	if err != nil {
		var zero0 *db.Analysis
		return zero0, err
	}
	return rv0, nil
}

// GetUser executes the generated GetUser query.
func (q *ReadQueries) GetUser(ctx context.Context, arg *db.GetUserParams) (*db.User, error) {
	rv0, err := q.main.GetUser(ctx, arg)
	if err != nil {
		var zero0 *db.User
		return zero0, err
	}
	return rv0, nil
}

// ListUsers executes the generated ListUsers query.
func (q *ReadQueries) ListUsers(ctx context.Context) ([]*db.User, error) {
	rv0, err := q.main.ListUsers(ctx)
	if err != nil {
		var zero0 []*db.User
		return zero0, err
	}
	return rv0, nil
}

// WriteQueries exposes primary-capable generated queries.
type WriteQueries struct {
	main    *db.Queries
	mirrors []*db.Queries
}

// NewWriteQueries creates a primary-capable query wrapper.
func NewWriteQueries(database db.DBTX) *WriteQueries {
	return newWriteQueries(db.New(database))
}

func newWriteQueries(q *db.Queries, mirrors ...*db.Queries) *WriteQueries {
	return &WriteQueries{main: q, mirrors: mirrors}
}

// WithTx returns a write wrapper that executes queries through tx.
func (q *WriteQueries) WithTx(tx pgx.Tx) *WriteQueries {
	return newWriteQueries(q.main.WithTx(tx))
}

// WithMirrors returns a copy that also writes to the supplied mirrors.
func (q *WriteQueries) WithMirrors(qs ...*WriteQueries) *WriteQueries {
	var mirrors []*db.Queries
	mirrors = append(mirrors, q.mirrors...)
	for _, mirror := range qs {
		if mirror == nil {
			continue
		}
		mirrors = append(mirrors, mirror.main)
		mirrors = append(mirrors, mirror.mirrors...)
	}
	return newWriteQueries(q.main, mirrors...)
}

func (q *WriteQueries) mirror(fn func(*db.Queries) error) error {
	for _, mirror := range q.mirrors {
		if err := fn(mirror); err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				continue
			}
			return err
		}
	}
	return nil
}

// CopyUsers executes the generated CopyUsers query.
func (q *WriteQueries) CopyUsers(ctx context.Context, arg []*db.CopyUsersParams) (int64, error) {
	rv0, err := q.main.CopyUsers(ctx, arg)
	if err != nil {
		var zero0 int64
		return zero0, err
	}
	mirrorErr := q.mirror(func(mirror *db.Queries) error {
		_, err := mirror.CopyUsers(ctx, arg)
		return err
	})
	return rv0, mirrorErr
}

// CreateUser executes the generated CreateUser query.
func (q *WriteQueries) CreateUser(ctx context.Context, arg *db.CreateUserParams) (*db.User, error) {
	rv0, err := q.main.CreateUser(ctx, arg)
	if err != nil {
		var zero0 *db.User
		return zero0, err
	}
	mirrorErr := q.mirror(func(mirror *db.Queries) error {
		_, err := mirror.CreateUser(ctx, arg)
		return err
	})
	return rv0, mirrorErr
}

// StoreQueries combines read-only and primary-capable generated queries.
type StoreQueries struct {
	*ReadQueries
	*WriteQueries
}

// NewStoreQueries creates a combined query wrapper.
func NewStoreQueries(database db.DBTX) *StoreQueries {
	return newStoreQueries(db.New(database))
}

func newStoreQueries(q *db.Queries, mirrors ...*db.Queries) *StoreQueries {
	return &StoreQueries{
		ReadQueries:  newReadQueries(q),
		WriteQueries: newWriteQueries(q, mirrors...),
	}
}

// WithTx returns a store wrapper that executes queries through tx.
func (q *StoreQueries) WithTx(tx pgx.Tx) *StoreQueries {
	return newStoreQueries(q.WriteQueries.main.WithTx(tx))
}

// WithMirrors returns a copy that also writes to the supplied mirrors.
func (q *StoreQueries) WithMirrors(qs ...*StoreQueries) *StoreQueries {
	var mirrors []*db.Queries
	mirrors = append(mirrors, q.WriteQueries.mirrors...)
	for _, mirror := range qs {
		if mirror == nil || mirror.WriteQueries == nil {
			continue
		}
		mirrors = append(mirrors, mirror.WriteQueries.main)
		mirrors = append(mirrors, mirror.WriteQueries.mirrors...)
	}
	return newStoreQueries(q.WriteQueries.main, mirrors...)
}

// NewStoreNode creates a pgmesh node backed by database.
func NewStoreNode(database db.DBTX) pgmesh.Node[*ReadQueries, *StoreQueries] {
	queries := db.New(database)
	return pgmesh.NewNode(newReadQueries(queries), newStoreQueries(queries))
}

// ShardResolver resolves generated query parameters to shard keys.
type ShardResolver[SK any] interface {
	// Tenant resolves the "tenant" shard route.
	Tenant(tenantID int64) SK
}

type routeOptions struct {
	primary bool
	tx      pgx.Tx
}

// RouteOption customizes routing for one generated query call.
type RouteOption func(*routeOptions)

// ReadFromPrimary routes a read query to the shard's primary.
func ReadFromPrimary() RouteOption {
	return func(options *routeOptions) { options.primary = true }
}

// WithTx routes a query through tx and suppresses write mirrors.
func WithTx(tx pgx.Tx) RouteOption {
	return func(options *routeOptions) { options.tx = tx }
}

func applyRouteOptions(options ...RouteOption) routeOptions {
	var result routeOptions
	for _, option := range options {
		if option != nil {
			option(&result)
		}
	}
	return result
}

// ShardedQueries routes generated queries through a pgmesh mesh.
type ShardedQueries[SK any] struct {
	mesh     *pgmesh.Mesh[*ReadQueries, *StoreQueries, SK]
	resolver ShardResolver[SK]
}

// NewShardedQueries creates a routed query facade.
func NewShardedQueries[SK any](mesh *pgmesh.Mesh[*ReadQueries, *StoreQueries, SK], resolver ShardResolver[SK]) *ShardedQueries[SK] {
	return &ShardedQueries[SK]{mesh: mesh, resolver: resolver}
}

// CreateUser executes the generated query on its resolved shard.
func (q *ShardedQueries[SK]) CreateUser(ctx context.Context, arg *db.CreateUserParams, routeOptions ...RouteOption) (*db.User, error) {
	ctx, queryTrace := q.mesh.StartQueryTrace(ctx, "CreateUser", pgmesh.QueryKindWrite)
	var queryErr error
	defer func() { queryTrace.End(queryErr) }()
	shardKey := q.resolver.Tenant(arg.TenantID)
	shard, err := q.mesh.Shard(shardKey)
	if err != nil {
		queryErr = err
		var zero0 *db.User
		return zero0, err
	}
	options := applyRouteOptions(routeOptions...)
	target := shard.Write()
	mode := pgmesh.RouteModePrimary
	writeMirrorCount := shard.WriteMirrorCount()
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
		writeMirrorCount = 0
	}
	queryTrace.SetRoute(shard.VShardIndex(), shard.Name(), mode, writeMirrorCount)
	var rv0 *db.User
	rv0, queryErr = target.CreateUser(ctx, arg)
	return rv0, queryErr
}

// GetAnalysis executes the generated query on its resolved shard.
func (q *ShardedQueries[SK]) GetAnalysis(ctx context.Context, arg *db.GetAnalysisParams, routeOptions ...RouteOption) (*db.Analysis, error) {
	ctx, queryTrace := q.mesh.StartQueryTrace(ctx, "GetAnalysis", pgmesh.QueryKindRead)
	var queryErr error
	defer func() { queryTrace.End(queryErr) }()
	shardKey := q.resolver.Tenant(arg.TenantID)
	shard, err := q.mesh.Shard(shardKey)
	if err != nil {
		queryErr = err
		var zero0 *db.Analysis
		return zero0, err
	}
	options := applyRouteOptions(routeOptions...)
	if options.tx != nil {
		queryTrace.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction, 0)
		var rv0 *db.Analysis
		rv0, queryErr = shard.Write().WithTx(options.tx).GetAnalysis(ctx, arg)
		return rv0, queryErr
	}
	if options.primary {
		queryTrace.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary, 0)
		var rv0 *db.Analysis
		rv0, queryErr = shard.Write().GetAnalysis(ctx, arg)
		return rv0, queryErr
	}
	queryTrace.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead, 0)
	var rv0 *db.Analysis
	rv0, queryErr = shard.Read().GetAnalysis(ctx, arg)
	return rv0, queryErr
}

// GetUser executes the generated query on its resolved shard.
func (q *ShardedQueries[SK]) GetUser(ctx context.Context, arg *db.GetUserParams, routeOptions ...RouteOption) (*db.User, error) {
	ctx, queryTrace := q.mesh.StartQueryTrace(ctx, "GetUser", pgmesh.QueryKindRead)
	var queryErr error
	defer func() { queryTrace.End(queryErr) }()
	shardKey := q.resolver.Tenant(arg.TenantID)
	shard, err := q.mesh.Shard(shardKey)
	if err != nil {
		queryErr = err
		var zero0 *db.User
		return zero0, err
	}
	options := applyRouteOptions(routeOptions...)
	if options.tx != nil {
		queryTrace.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction, 0)
		var rv0 *db.User
		rv0, queryErr = shard.Write().WithTx(options.tx).GetUser(ctx, arg)
		return rv0, queryErr
	}
	if options.primary {
		queryTrace.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary, 0)
		var rv0 *db.User
		rv0, queryErr = shard.Write().GetUser(ctx, arg)
		return rv0, queryErr
	}
	queryTrace.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead, 0)
	var rv0 *db.User
	rv0, queryErr = shard.Read().GetUser(ctx, arg)
	return rv0, queryErr
}
