// Code generated by pgmesh. DO NOT EDIT.

package store

import (
	"context"
	"database/sql"
	"errors"
	sqlcstore "github.com/clnv/pgmesh"
	db "github.com/clnv/pgmesh/integration/fixture/separate/internal"
	"github.com/jackc/pgx/v5"
)

type ReadQuerier interface {
	GetAnalysis(ctx context.Context, arg *db.GetAnalysisParams) (*db.Analysis, error)
	GetUser(ctx context.Context, arg *db.GetUserParams) (*db.User, error)
	ListUsers(ctx context.Context) ([]*db.User, error)
}

type WriteQuerier interface {
	CopyUsers(ctx context.Context, arg []*db.CopyUsersParams) (int64, error)
	CreateUser(ctx context.Context, arg *db.CreateUserParams) (*db.User, error)
}

type StoreQuerier interface {
	ReadQuerier
	WriteQuerier
}

var _ ReadQuerier = (*ReadQueries)(nil)
var _ WriteQuerier = (*WriteQueries)(nil)
var _ StoreQuerier = (*StoreQueries)(nil)
var _ db.Querier = (*StoreQueries)(nil)

type ReadQueries struct {
	main *db.Queries
}

func NewReadQueries(database db.DBTX) *ReadQueries {
	return newReadQueries(db.New(database))
}

func newReadQueries(q *db.Queries) *ReadQueries {
	return &ReadQueries{main: q}
}

func (q *ReadQueries) WithTx(tx pgx.Tx) *ReadQueries {
	return newReadQueries(q.main.WithTx(tx))
}

func (q *ReadQueries) GetAnalysis(ctx context.Context, arg *db.GetAnalysisParams) (*db.Analysis, error) {
	rv0, err := q.main.GetAnalysis(ctx, arg)
	if err != nil {
		var zero0 *db.Analysis
		return zero0, err
	}
	return rv0, nil
}

func (q *ReadQueries) GetUser(ctx context.Context, arg *db.GetUserParams) (*db.User, error) {
	rv0, err := q.main.GetUser(ctx, arg)
	if err != nil {
		var zero0 *db.User
		return zero0, err
	}
	return rv0, nil
}

func (q *ReadQueries) ListUsers(ctx context.Context) ([]*db.User, error) {
	rv0, err := q.main.ListUsers(ctx)
	if err != nil {
		var zero0 []*db.User
		return zero0, err
	}
	return rv0, nil
}

type WriteQueries struct {
	main    *db.Queries
	mirrors []*db.Queries
}

func NewWriteQueries(database db.DBTX) *WriteQueries {
	return newWriteQueries(db.New(database))
}

func newWriteQueries(q *db.Queries, mirrors ...*db.Queries) *WriteQueries {
	return &WriteQueries{main: q, mirrors: mirrors}
}

func (q *WriteQueries) WithTx(tx pgx.Tx) *WriteQueries {
	return newWriteQueries(q.main.WithTx(tx))
}

func (q *WriteQueries) WithMirrors(qs ...*WriteQueries) *WriteQueries {
	var mirrors []*db.Queries
	mirrors = append(mirrors, q.mirrors...)
	for _, mirror := range qs {
		if mirror == nil {
			continue
		}
		mirrors = append(mirrors, mirror.main)
		mirrors = append(mirrors, mirror.mirrors...)
	}
	return newWriteQueries(q.main, mirrors...)
}

func (q *WriteQueries) mirror(fn func(*db.Queries) error) error {
	for _, mirror := range q.mirrors {
		if err := fn(mirror); err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				continue
			}
			return err
		}
	}
	return nil
}

func (q *WriteQueries) CopyUsers(ctx context.Context, arg []*db.CopyUsersParams) (int64, error) {
	rv0, err := q.main.CopyUsers(ctx, arg)
	if err != nil {
		var zero0 int64
		return zero0, err
	}
	mirrorErr := q.mirror(func(mirror *db.Queries) error {
		_, err := mirror.CopyUsers(ctx, arg)
		return err
	})
	return rv0, mirrorErr
}

func (q *WriteQueries) CreateUser(ctx context.Context, arg *db.CreateUserParams) (*db.User, error) {
	rv0, err := q.main.CreateUser(ctx, arg)
	if err != nil {
		var zero0 *db.User
		return zero0, err
	}
	mirrorErr := q.mirror(func(mirror *db.Queries) error {
		_, err := mirror.CreateUser(ctx, arg)
		return err
	})
	return rv0, mirrorErr
}

type StoreQueries struct {
	*ReadQueries
	*WriteQueries
}

func NewStoreQueries(database db.DBTX) *StoreQueries {
	return newStoreQueries(db.New(database))
}

func newStoreQueries(q *db.Queries, mirrors ...*db.Queries) *StoreQueries {
	return &StoreQueries{
		ReadQueries:  newReadQueries(q),
		WriteQueries: newWriteQueries(q, mirrors...),
	}
}

func (q *StoreQueries) WithTx(tx pgx.Tx) *StoreQueries {
	return newStoreQueries(q.WriteQueries.main.WithTx(tx))
}

func (q *StoreQueries) WithMirrors(qs ...*StoreQueries) *StoreQueries {
	var mirrors []*db.Queries
	mirrors = append(mirrors, q.WriteQueries.mirrors...)
	for _, mirror := range qs {
		if mirror == nil || mirror.WriteQueries == nil {
			continue
		}
		mirrors = append(mirrors, mirror.WriteQueries.main)
		mirrors = append(mirrors, mirror.WriteQueries.mirrors...)
	}
	return newStoreQueries(q.WriteQueries.main, mirrors...)
}

func NewStoreNode(database db.DBTX) sqlcstore.Node[*ReadQueries, *StoreQueries] {
	queries := db.New(database)
	return sqlcstore.NewNode(newReadQueries(queries), newStoreQueries(queries))
}

type ShardResolver[SK any] interface {
	Tenant(tenantID int64) SK
}

type routeOptions struct {
	primary bool
	tx      pgx.Tx
}

type RouteOption func(*routeOptions)

func ReadFromPrimary() RouteOption {
	return func(options *routeOptions) { options.primary = true }
}

func WithTx(tx pgx.Tx) RouteOption {
	return func(options *routeOptions) { options.tx = tx }
}

func applyRouteOptions(options ...RouteOption) routeOptions {
	var result routeOptions
	for _, option := range options {
		if option != nil {
			option(&result)
		}
	}
	return result
}

type ShardedQueries[SK any] struct {
	mesh     *sqlcstore.Mesh[*ReadQueries, *StoreQueries, SK]
	resolver ShardResolver[SK]
}

func NewShardedQueries[SK any](mesh *sqlcstore.Mesh[*ReadQueries, *StoreQueries, SK], resolver ShardResolver[SK]) *ShardedQueries[SK] {
	return &ShardedQueries[SK]{mesh: mesh, resolver: resolver}
}

func (q *ShardedQueries[SK]) CreateUser(ctx context.Context, arg *db.CreateUserParams, routeOptions ...RouteOption) (*db.User, error) {
	shardKey := q.resolver.Tenant(arg.TenantID)
	shard, err := q.mesh.Shard(shardKey)
	if err != nil {
		var zero0 *db.User
		return zero0, err
	}
	options := applyRouteOptions(routeOptions...)
	target := shard.Write()
	if options.tx != nil {
		target = target.WithTx(options.tx)
	}
	return target.CreateUser(ctx, arg)
}

func (q *ShardedQueries[SK]) GetAnalysis(ctx context.Context, arg *db.GetAnalysisParams, routeOptions ...RouteOption) (*db.Analysis, error) {
	shardKey := q.resolver.Tenant(arg.TenantID)
	shard, err := q.mesh.Shard(shardKey)
	if err != nil {
		var zero0 *db.Analysis
		return zero0, err
	}
	options := applyRouteOptions(routeOptions...)
	if options.tx != nil {
		return shard.Write().WithTx(options.tx).GetAnalysis(ctx, arg)
	}
	if options.primary {
		return shard.Write().GetAnalysis(ctx, arg)
	}
	return shard.Read().GetAnalysis(ctx, arg)
}

func (q *ShardedQueries[SK]) GetUser(ctx context.Context, arg *db.GetUserParams, routeOptions ...RouteOption) (*db.User, error) {
	shardKey := q.resolver.Tenant(arg.TenantID)
	shard, err := q.mesh.Shard(shardKey)
	if err != nil {
		var zero0 *db.User
		return zero0, err
	}
	options := applyRouteOptions(routeOptions...)
	if options.tx != nil {
		return shard.Write().WithTx(options.tx).GetUser(ctx, arg)
	}
	if options.primary {
		return shard.Write().GetUser(ctx, arg)
	}
	return shard.Read().GetUser(ctx, arg)
}
