// Code generated by pgmesh. DO NOT EDIT.

package store

import (
	"context"
	db "github.com/clnv/pgmesh/integration/fixture/separate/internal"
)

// readQuerier exposes generated read queries.
type readQuerier interface {
	// GetAnalysis executes the generated GetAnalysis query.
	GetAnalysis(ctx context.Context, arg *db.GetAnalysisParams) (*db.Analysis, error)
	// GetUser executes the generated GetUser query.
	GetUser(ctx context.Context, arg *db.GetUserParams) (*db.User, error)
}

// writeQuerier exposes generated write queries.
type writeQuerier interface {
	// CreateUser executes the generated CreateUser query.
	CreateUser(ctx context.Context, arg *db.CreateUserParams) (*db.User, error)
}

// Store is the topology-independent generated query API.
type Store interface {
	// CreateUser executes the generated CreateUser query.
	CreateUser(ctx context.Context, arg *db.CreateUserParams, storeOptions ...QueryOption) (*db.User, error)
	// GetAnalysis executes the generated GetAnalysis query.
	GetAnalysis(ctx context.Context, arg *db.GetAnalysisParams, storeOptions ...QueryOption) (*db.Analysis, error)
	// GetUser executes the generated GetUser query.
	GetUser(ctx context.Context, arg *db.GetUserParams, storeOptions ...QueryOption) (*db.User, error)
}

var _ readQuerier = (*readQueries)(nil)
var _ writeQuerier = (*writeQueries)(nil)
var _ db.Querier = (*queryStore)(nil)

// ShardResolver resolves generated query parameters to shard keys.
type ShardResolver[SK any] interface {
	// Tenant resolves the "tenant" shard route.
	Tenant(tenantID int64) SK
}
