// Code generated by pgmesh. DO NOT EDIT.

package store

import (
	"context"
	"database/sql"
	"errors"
	db "github.com/clnv/pgmesh/integration/fixture/separate/internal"
	"github.com/jackc/pgx/v5"
)

// writeQueries exposes primary-capable generated queries.
type writeQueries struct {
	main    *db.Queries
	mirrors []*db.Queries
}

func newWriteQueries(q *db.Queries, mirrors ...*db.Queries) *writeQueries {
	return &writeQueries{main: q, mirrors: mirrors}
}

// WithTx returns a write wrapper that executes queries through tx.
func (q *writeQueries) WithTx(tx pgx.Tx) *writeQueries {
	return newWriteQueries(q.main.WithTx(tx))
}

// WithMirrors returns a copy that also writes to the supplied mirrors.
func (q *writeQueries) WithMirrors(qs ...*writeQueries) *writeQueries {
	var mirrors []*db.Queries
	mirrors = append(mirrors, q.mirrors...)
	for _, mirror := range qs {
		if mirror == nil {
			continue
		}
		mirrors = append(mirrors, mirror.main)
		mirrors = append(mirrors, mirror.mirrors...)
	}
	return newWriteQueries(q.main, mirrors...)
}

func (q *writeQueries) mirror(fn func(*db.Queries) error) error {
	for _, mirror := range q.mirrors {
		if err := fn(mirror); err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				continue
			}
			return err
		}
	}
	return nil
}

// CreateUser executes the generated CreateUser query.
func (q *writeQueries) CreateUser(ctx context.Context, arg *db.CreateUserParams) (*db.User, error) {
	rv0, err := q.main.CreateUser(ctx, arg)
	if err != nil {
		var zero0 *db.User
		return zero0, err
	}
	mirrorErr := q.mirror(func(mirror *db.Queries) error {
		_, err := mirror.CreateUser(ctx, arg)
		return err
	})
	return rv0, mirrorErr
}
