// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package fixture

import (
	"context"
)

type CopyUsersParams struct {
	ID       int64
	TenantID int64
	Name     string
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, tenant_id, name)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name
`

type CreateUserParams struct {
	ID       int64
	TenantID int64
	Name     string
}

// kind: write
// shard: tenant(tenant_id)
func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.TenantID, arg.Name)
	var i User
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return &i, err
}

const getAnalysis = `-- name: GetAnalysis :one
SELECT id, tenant_id, summary, state, source, active_window
FROM analyses
WHERE tenant_id = $1 AND id = $2
`

type GetAnalysisParams struct {
	TenantID int64
	ID       int64
}

// kind: read
// shard: tenant(tenant_id)
func (q *Queries) GetAnalysis(ctx context.Context, arg *GetAnalysisParams) (*Analysis, error) {
	row := q.db.QueryRow(ctx, getAnalysis, arg.TenantID, arg.ID)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Description,
		&i.State,
		&i.Source,
		&i.ActiveWindow,
	)
	return &i, err
}

const getUser = `-- name: GetUser :one
SELECT id, tenant_id, name
FROM users
WHERE tenant_id = $1 AND id = $2
`

type GetUserParams struct {
	TenantID int64
	ID       int64
}

// kind: read
// shard: tenant(tenant_id)
func (q *Queries) GetUser(ctx context.Context, arg *GetUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, getUser, arg.TenantID, arg.ID)
	var i User
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, name
FROM users
ORDER BY id
`

// kind: read
func (q *Queries) ListUsers(ctx context.Context) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.TenantID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
