// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package fixture

import (
	"context"
)

type Querier interface {
	// kind: write
	CopyUsers(ctx context.Context, arg []*CopyUsersParams) (int64, error)
	// kind: write
	// shard: tenant(tenant_id)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	// kind: read
	// shard: tenant(tenant_id)
	GetAnalysis(ctx context.Context, arg *GetAnalysisParams) (*Analysis, error)
	// kind: read
	// shard: tenant(tenant_id)
	GetUser(ctx context.Context, arg *GetUserParams) (*User, error)
	// kind: read
	ListUsers(ctx context.Context) ([]*User, error)
}

var _ Querier = (*Queries)(nil)
