// Code generated by pgmesh. DO NOT EDIT.

package fixture

import (
	"context"
)

// readQuerier exposes generated read queries.
type readQuerier interface {
	// GetAnalysis executes the generated GetAnalysis query.
	GetAnalysis(ctx context.Context, arg *GetAnalysisParams) (*Analysis, error)
	// GetUser executes the generated GetUser query.
	GetUser(ctx context.Context, arg *GetUserParams) (*User, error)
}

// writeQuerier exposes generated write queries.
type writeQuerier interface {
	// CreateUser executes the generated CreateUser query.
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	// UpdateUserName executes the generated UpdateUserName query.
	UpdateUserName(ctx context.Context, arg *UpdateUserNameParams) (*User, error)
}

// Store is the topology-independent generated query API.
type Store interface {
	// CreateUser executes the generated CreateUser query.
	CreateUser(ctx context.Context, arg *CreateUserParams, storeOptions ...QueryOption) (*User, error)
	// GetAnalysis executes the generated GetAnalysis query.
	GetAnalysis(ctx context.Context, arg *GetAnalysisParams, storeOptions ...QueryOption) (*Analysis, error)
	// GetUser executes the generated GetUser query.
	GetUser(ctx context.Context, arg *GetUserParams, storeOptions ...QueryOption) (*User, error)
	// UpdateUserName executes the generated UpdateUserName query.
	UpdateUserName(ctx context.Context, arg *UpdateUserNameParams, storeOptions ...QueryOption) (*User, error)
}

var _ readQuerier = (*readQueries)(nil)
var _ writeQuerier = (*writeQueries)(nil)
var _ Querier = (*queryStore)(nil)

// ShardResolver resolves generated query parameters to shard keys.
type ShardResolver[SK any] interface {
	// Tenant resolves the "tenant" shard route.
	Tenant(tenantID int64) SK
}
