// Code generated by pgmesh. DO NOT EDIT.

package fixture

import (
	"context"
	"fmt"
	pgmesh "github.com/clnv/pgmesh"
	"github.com/jackc/pgx/v5"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
	"log/slog"
)

type queryOptions struct {
	primary bool
	tx      pgx.Tx
}

// QueryOption customizes routing for one generated query call.
type QueryOption func(*queryOptions)

// ReadFromPrimary routes a read query to the primary database.
func ReadFromPrimary() QueryOption {
	return func(options *queryOptions) { options.primary = true }
}

// WithTx executes a query through tx and suppresses write mirrors.
func WithTx(tx pgx.Tx) QueryOption {
	return func(options *queryOptions) { options.tx = tx }
}

func applyQueryOptions(options ...QueryOption) queryOptions {
	var result queryOptions
	for _, option := range options {
		if option != nil {
			option(&result)
		}
	}
	return result
}

type queryStore struct {
	*readQueries
	*writeQueries
}

func newQueryStore(q *Queries, mirrors ...*Queries) *queryStore {
	return &queryStore{
		readQueries:  newReadQueries(q),
		writeQueries: newWriteQueries(q, mirrors...),
	}
}

// WithTx returns a store wrapper that executes queries through tx.
func (q *queryStore) WithTx(tx pgx.Tx) *queryStore {
	return newQueryStore(q.writeQueries.main.WithTx(tx))
}

// WithMirrors returns a copy that also writes to the supplied mirrors.
func (q *queryStore) WithMirrors(qs ...*queryStore) *queryStore {
	var mirrors []*Queries
	mirrors = append(mirrors, q.writeQueries.mirrors...)
	for _, mirror := range qs {
		if mirror == nil || mirror.writeQueries == nil {
			continue
		}
		mirrors = append(mirrors, mirror.writeQueries.main)
		mirrors = append(mirrors, mirror.writeQueries.mirrors...)
	}
	return newQueryStore(q.writeQueries.main, mirrors...)
}

func newStoreNode(database DBTX) pgmesh.Node[*readQueries, *queryStore] {
	queries := New(database)
	return pgmesh.NewNode(newReadQueries(queries), newQueryStore(queries))
}

// StoreConfig is an opaque database-topology configuration for Store.
type StoreConfig interface {
	buildStore(context.Context) (Store, error)
}

// DatabaseConfig configures a single primary, optional read replicas, and optional write mirrors.
type DatabaseConfig struct {
	// Name identifies the database in telemetry; empty defaults to "default".
	Name string
	// Primary serves writes and explicit primary reads. The caller owns its lifecycle.
	Primary DBTX
	// Replicas serve ordinary reads in round-robin order. The caller owns their lifecycles.
	Replicas []DBTX
	// Mirrors synchronously receive writes in slice order after the primary succeeds.
	Mirrors []DBTX
	// TracerProvider records routed query spans; nil uses the global provider.
	TracerProvider trace.TracerProvider
	// MeterProvider records routed query metrics; nil uses the global provider.
	MeterProvider metric.MeterProvider
	// Logger receives routed query debug logs; nil disables logging.
	Logger *slog.Logger
}

type databaseStoreConfig struct{ config DatabaseConfig }

// Database returns an opaque configuration for a non-sharded store.
func Database(config DatabaseConfig) StoreConfig {
	return databaseStoreConfig{config: config}
}

// NewStore creates the generated query API from an opaque topology configuration.
func NewStore(ctx context.Context, config StoreConfig) (Store, error) {
	if config == nil {
		return nil, fmt.Errorf("pgmesh: store config is nil")
	}
	return config.buildStore(ctx)
}

type meshStore[SK any] struct {
	mesh     *pgmesh.Mesh[*readQueries, *queryStore, SK]
	resolver ShardResolver[SK]
}

var _ Store = (*meshStore[uint8])(nil)

func (c databaseStoreConfig) buildStore(_ context.Context) (Store, error) {
	config := c.config
	if config.Name == "" {
		config.Name = "default"
	}
	if config.Primary == nil {
		return nil, fmt.Errorf("pgmesh: database primary is nil")
	}
	for index, database := range config.Replicas {
		if database == nil {
			return nil, fmt.Errorf("pgmesh: database replica %d is nil", index)
		}
	}
	for index, database := range config.Mirrors {
		if database == nil {
			return nil, fmt.Errorf("pgmesh: database mirror %d is nil", index)
		}
	}
	primary := newStoreNode(config.Primary)
	replicas := make([]pgmesh.Node[*readQueries, *queryStore], 0, len(config.Replicas))
	for _, database := range config.Replicas {
		replicas = append(replicas, newStoreNode(database))
	}
	replicaSet := pgmesh.NewReplicaSet(config.Name, primary, replicas)
	mirrors := make([]*queryStore, 0, len(config.Mirrors))
	for _, database := range config.Mirrors {
		mirrors = append(mirrors, newStoreNode(database).Writer())
	}
	replicaSet = replicaSet.WithWriteMirrors(mirrors...)
	mesh, err := pgmesh.NewBuilder[*readQueries, *queryStore, uint8](1).
		WithHasher(pgmesh.ConstantShardHashFor[uint8](0)).
		WithTracerProvider(config.TracerProvider).
		WithMeterProvider(config.MeterProvider).
		WithLogger(config.Logger).
		Link(0, replicaSet).
		Build()
	if err != nil {
		return nil, err
	}
	return &meshStore[uint8]{mesh: mesh}, nil
}

// CreateUser executes the generated query on its target shard.
func (q *meshStore[SK]) CreateUser(ctx context.Context, arg *CreateUserParams, storeOptions ...QueryOption) (result *User, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.mesh.StartSpan(ctx, "Store", "CreateUser", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.resolver != nil {
		shardKey = q.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	target := shard.Write()
	mode := pgmesh.RouteModePrimary
	writeMirrorCount := shard.WriteMirrorCount()
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
		writeMirrorCount = 0
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), mode, writeMirrorCount)
	return target.CreateUser(ctx, arg)
}

// GetAnalysis executes the generated query on its target shard.
func (q *meshStore[SK]) GetAnalysis(ctx context.Context, arg *GetAnalysisParams, storeOptions ...QueryOption) (result *Analysis, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.mesh.StartSpan(ctx, "Store", "GetAnalysis", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.resolver != nil {
		shardKey = q.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Transactional reads must use their transaction.
	if options.tx != nil {
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction, 0)
		return shard.Write().WithTx(options.tx).GetAnalysis(ctx, arg)
	}

	// Explicit primary reads bypass replicas.
	if options.primary {
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary, 0)
		return shard.Write().GetAnalysis(ctx, arg)
	}

	// Ordinary reads use the shard's replica route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead, 0)
	return shard.Read().GetAnalysis(ctx, arg)
}

// GetUser executes the generated query on its target shard.
func (q *meshStore[SK]) GetUser(ctx context.Context, arg *GetUserParams, storeOptions ...QueryOption) (result *User, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.mesh.StartSpan(ctx, "Store", "GetUser", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.resolver != nil {
		shardKey = q.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Transactional reads must use their transaction.
	if options.tx != nil {
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction, 0)
		return shard.Write().WithTx(options.tx).GetUser(ctx, arg)
	}

	// Explicit primary reads bypass replicas.
	if options.primary {
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary, 0)
		return shard.Write().GetUser(ctx, arg)
	}

	// Ordinary reads use the shard's replica route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead, 0)
	return shard.Read().GetUser(ctx, arg)
}

// UpdateUserName executes the generated query on its target shard.
func (q *meshStore[SK]) UpdateUserName(ctx context.Context, arg *UpdateUserNameParams, storeOptions ...QueryOption) (result *User, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.mesh.StartSpan(ctx, "Store", "UpdateUserName", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.resolver != nil {
		shardKey = q.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	target := shard.Write()
	mode := pgmesh.RouteModePrimary
	writeMirrorCount := shard.WriteMirrorCount()
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
		writeMirrorCount = 0
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), mode, writeMirrorCount)
	return target.UpdateUserName(ctx, arg)
}
