// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package fixture

import (
	"context"
)

type Querier interface {
	// kind: write
	// shard: tenant(tenant_id)
	// store: Users
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	// kind: read
	// shard: tenant(tenant_id)
	// store: Analyses
	GetAnalysis(ctx context.Context, arg *GetAnalysisParams) (*Analysis, error)
	// kind: read
	// shard: tenant(tenant_id)
	// store: Users
	GetUser(ctx context.Context, arg *GetUserParams) (*User, error)
	// kind: write
	// shard: tenant(tenant_id)
	// store: Users
	UpdateUserName(ctx context.Context, arg *UpdateUserNameParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
