// Code generated by pgmesh. DO NOT EDIT.

package fixture

import (
	"context"
	"fmt"
	pgmesh "github.com/clnv/pgmesh"
	"github.com/jackc/pgx/v5"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
	"log/slog"
)

type queryOptions struct {
	primary bool
	tx      pgx.Tx
}

// QueryOption customizes routing for one generated query call.
type QueryOption func(*queryOptions)

// ReadFromPrimary routes a read query to the primary database.
func ReadFromPrimary() QueryOption {
	return func(options *queryOptions) { options.primary = true }
}

// WithTx executes a query through tx and suppresses write mirrors.
func WithTx(tx pgx.Tx) QueryOption {
	return func(options *queryOptions) { options.tx = tx }
}

func applyQueryOptions(options ...QueryOption) queryOptions {
	var result queryOptions
	for _, option := range options {
		if option != nil {
			option(&result)
		}
	}
	return result
}

type queryStore struct {
	*readQueries
	*writeQueries
}

func newQueryStore(q *Queries, mirrors ...*Queries) *queryStore {
	return &queryStore{
		readQueries:  newReadQueries(q),
		writeQueries: newWriteQueries(q, mirrors...),
	}
}

// WithTx returns a store wrapper that executes queries through tx.
func (q *queryStore) WithTx(tx pgx.Tx) *queryStore {
	return newQueryStore(q.writeQueries.main.WithTx(tx))
}

// WithMirrors returns a copy that also writes to the supplied mirrors.
func (q *queryStore) WithMirrors(qs ...*queryStore) *queryStore {
	var mirrors []*Queries
	mirrors = append(mirrors, q.writeQueries.mirrors...)
	for _, mirror := range qs {
		if mirror == nil || mirror.writeQueries == nil {
			continue
		}
		mirrors = append(mirrors, mirror.writeQueries.main)
		mirrors = append(mirrors, mirror.writeQueries.mirrors...)
	}
	return newQueryStore(q.writeQueries.main, mirrors...)
}

func newStoreNode(database DBTX) pgmesh.Node[*readQueries, *queryStore] {
	queries := New(database)
	return pgmesh.NewNode(newReadQueries(queries), newQueryStore(queries))
}

type storeOptions struct {
	tracerProvider trace.TracerProvider
	meterProvider  metric.MeterProvider
	logger         *slog.Logger
}

// StoreOption customizes telemetry for a generated store.
type StoreOption func(*storeOptions)

// WithTracerProvider configures the provider used for routed query spans.
// A nil provider uses the global OpenTelemetry tracer provider.
func WithTracerProvider(provider trace.TracerProvider) StoreOption {
	return func(options *storeOptions) { options.tracerProvider = provider }
}

// WithMeterProvider configures the provider used for routed query metrics.
// A nil provider uses the global OpenTelemetry meter provider.
func WithMeterProvider(provider metric.MeterProvider) StoreOption {
	return func(options *storeOptions) { options.meterProvider = provider }
}

// WithLogger configures optional structured logging for routed queries.
// A nil logger disables logging.
func WithLogger(logger *slog.Logger) StoreOption {
	return func(options *storeOptions) { options.logger = logger }
}

func applyStoreOptions(options ...StoreOption) (storeOptions, error) {
	var result storeOptions
	for index, option := range options {
		if option == nil {
			return storeOptions{}, fmt.Errorf("pgmesh: store option %d is nil", index)
		}
		option(&result)
	}
	return result, nil
}

// Topology is an opaque database topology for Store.
type Topology interface {
	buildStore(context.Context, storeOptions) (Store, error)
}

type singletonConfig struct {
	name     string
	primary  DBTX
	replicas []DBTX
	mirrors  []DBTX
}

// SingletonOption customizes a single-database topology.
type SingletonOption func(*singletonConfig)

// WithDatabaseName identifies the database in telemetry.
// An empty name defaults to "default".
func WithDatabaseName(name string) SingletonOption {
	return func(config *singletonConfig) { config.name = name }
}

// WithReadReplicas appends databases used for round-robin reads.
func WithReadReplicas(databases ...DBTX) SingletonOption {
	replicas := append([]DBTX(nil), databases...)
	return func(config *singletonConfig) { config.replicas = append(config.replicas, replicas...) }
}

// WithWriteMirrors appends databases that synchronously receive writes.
func WithWriteMirrors(databases ...DBTX) SingletonOption {
	mirrors := append([]DBTX(nil), databases...)
	return func(config *singletonConfig) { config.mirrors = append(config.mirrors, mirrors...) }
}

type singletonTopology struct {
	config singletonConfig
	err    error
}

// Singleton returns a topology with one primary database.
func Singleton(primary DBTX, options ...SingletonOption) Topology {
	config := singletonConfig{name: "default", primary: primary}
	for index, option := range options {
		if option == nil {
			return singletonTopology{err: fmt.Errorf("pgmesh: singleton option %d is nil", index)}
		}
		option(&config)
	}
	return singletonTopology{config: config}
}

// NewStore creates the generated query API from an opaque topology configuration.
func NewStore(ctx context.Context, topology Topology, options ...StoreOption) (Store, error) {
	if topology == nil {
		return nil, fmt.Errorf("pgmesh: topology is nil")
	}
	storeOptions, err := applyStoreOptions(options...)
	if err != nil {
		return nil, err
	}
	return topology.buildStore(ctx, storeOptions)
}

type meshStore[SK any] struct {
	mesh     *pgmesh.Mesh[*readQueries, *queryStore, SK]
	resolver ShardResolver[SK]
}

var _ Store = (*meshStore[uint8])(nil)

type groupedMeshStore[SK any] struct {
	store *meshStore[SK]
}

var _ Analyses = (*groupedMeshStore[uint8])(nil)
var _ QueryMessage = (*groupedMeshStore[uint8])(nil)
var _ Users = (*groupedMeshStore[uint8])(nil)

// Analyses returns the Analyses query group.
func (q *meshStore[SK]) Analyses() Analyses {
	return &groupedMeshStore[SK]{store: q}
}

// QueryMessage returns the QueryMessage query group.
func (q *meshStore[SK]) QueryMessage() QueryMessage {
	return &groupedMeshStore[SK]{store: q}
}

// Users returns the Users query group.
func (q *meshStore[SK]) Users() Users {
	return &groupedMeshStore[SK]{store: q}
}

func (c singletonTopology) buildStore(_ context.Context, options storeOptions) (Store, error) {
	if c.err != nil {
		return nil, c.err
	}
	config := c.config
	if config.name == "" {
		config.name = "default"
	}
	if config.primary == nil {
		return nil, fmt.Errorf("pgmesh: database primary is nil")
	}
	for index, database := range config.replicas {
		if database == nil {
			return nil, fmt.Errorf("pgmesh: database replica %d is nil", index)
		}
	}
	for index, database := range config.mirrors {
		if database == nil {
			return nil, fmt.Errorf("pgmesh: database mirror %d is nil", index)
		}
	}
	primary := newStoreNode(config.primary)
	replicas := make([]pgmesh.Node[*readQueries, *queryStore], 0, len(config.replicas))
	for _, database := range config.replicas {
		replicas = append(replicas, newStoreNode(database))
	}
	replicaSet := pgmesh.NewReplicaSet(config.name, primary, replicas)
	mirrors := make([]*queryStore, 0, len(config.mirrors))
	for _, database := range config.mirrors {
		mirrors = append(mirrors, newStoreNode(database).Writer())
	}
	replicaSet = replicaSet.WithWriteMirrors(mirrors...)
	mesh, err := pgmesh.NewBuilder[*readQueries, *queryStore, uint8](1).
		WithHasher(pgmesh.ConstantShardHashFor[uint8](0)).
		WithTracerProvider(options.tracerProvider).
		WithMeterProvider(options.meterProvider).
		WithLogger(options.logger).
		Link(0, replicaSet).
		Build()
	if err != nil {
		return nil, err
	}
	return &meshStore[uint8]{mesh: mesh}, nil
}

// CreateUser executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) CreateUser(ctx context.Context, arg *CreateUserParams, storeOptions ...QueryOption) (result *User, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Store", "CreateUser", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	target := shard.Write()
	mode := pgmesh.RouteModePrimary
	writeMirrorCount := shard.WriteMirrorCount()
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
		writeMirrorCount = 0
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), mode, writeMirrorCount)
	return target.CreateUser(ctx, arg)
}

// GetAnalysis executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) GetAnalysis(ctx context.Context, arg *GetAnalysisParams, storeOptions ...QueryOption) (result *Analysis, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Store", "GetAnalysis", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Transactional reads must use their transaction.
	if options.tx != nil {
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction, 0)
		return shard.Write().WithTx(options.tx).GetAnalysis(ctx, arg)
	}

	// Explicit primary reads bypass replicas.
	if options.primary {
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary, 0)
		return shard.Write().GetAnalysis(ctx, arg)
	}

	// Ordinary reads use the shard's replica route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead, 0)
	return shard.Read().GetAnalysis(ctx, arg)
}

// GetTenantUserAnalysis executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) GetTenantUserAnalysis(ctx context.Context, arg *GetTenantUserAnalysisShardParams, storeOptions ...QueryOption) (result *GetTenantUserAnalysisRow, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Store", "GetTenantUserAnalysis", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Transactional reads must use their transaction.
	if options.tx != nil {
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction, 0)
		return shard.Write().WithTx(options.tx).GetTenantUserAnalysis(ctx, arg.Arg)
	}

	// Explicit primary reads bypass replicas.
	if options.primary {
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary, 0)
		return shard.Write().GetTenantUserAnalysis(ctx, arg.Arg)
	}

	// Ordinary reads use the shard's replica route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead, 0)
	return shard.Read().GetTenantUserAnalysis(ctx, arg.Arg)
}

// GetUser executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) GetUser(ctx context.Context, arg *GetUserParams, storeOptions ...QueryOption) (result *User, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Store", "GetUser", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Transactional reads must use their transaction.
	if options.tx != nil {
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction, 0)
		return shard.Write().WithTx(options.tx).GetUser(ctx, arg)
	}

	// Explicit primary reads bypass replicas.
	if options.primary {
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary, 0)
		return shard.Write().GetUser(ctx, arg)
	}

	// Ordinary reads use the shard's replica route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead, 0)
	return shard.Read().GetUser(ctx, arg)
}

// ListP2PMessageIDsByChat executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) ListP2PMessageIDsByChat(ctx context.Context, arg *ListP2PMessageIDsByChatShardParams, storeOptions ...QueryOption) (result []interface{}, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Store", "ListP2PMessageIDsByChat", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Messagekey(arg.Arg.UserID, arg.ToUserOrGroupID, arg.InGroup)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Transactional reads must use their transaction.
	if options.tx != nil {
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction, 0)
		return shard.Write().WithTx(options.tx).ListP2PMessageIDsByChat(ctx, arg.Arg)
	}

	// Explicit primary reads bypass replicas.
	if options.primary {
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary, 0)
		return shard.Write().ListP2PMessageIDsByChat(ctx, arg.Arg)
	}

	// Ordinary reads use the shard's replica route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead, 0)
	return shard.Read().ListP2PMessageIDsByChat(ctx, arg.Arg)
}

// ListP2PMessagesByChat executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) ListP2PMessagesByChat(ctx context.Context, arg *ListP2PMessagesByChatShardParams, storeOptions ...QueryOption) (result []*Message, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Store", "ListP2PMessagesByChat", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Messagekey(arg.Arg.UserID, arg.ToUserOrGroupID, arg.InGroup)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Transactional reads must use their transaction.
	if options.tx != nil {
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction, 0)
		return shard.Write().WithTx(options.tx).ListP2PMessagesByChat(ctx, arg.Arg)
	}

	// Explicit primary reads bypass replicas.
	if options.primary {
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary, 0)
		return shard.Write().ListP2PMessagesByChat(ctx, arg.Arg)
	}

	// Ordinary reads use the shard's replica route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead, 0)
	return shard.Read().ListP2PMessagesByChat(ctx, arg.Arg)
}

// UpdateUserName executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) UpdateUserName(ctx context.Context, arg *UpdateUserNameParams, storeOptions ...QueryOption) (result *User, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Store", "UpdateUserName", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	target := shard.Write()
	mode := pgmesh.RouteModePrimary
	writeMirrorCount := shard.WriteMirrorCount()
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
		writeMirrorCount = 0
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), mode, writeMirrorCount)
	return target.UpdateUserName(ctx, arg)
}
