// Code generated by pgmesh. DO NOT EDIT.

package exampledb

import (
	"context"
	"database/sql"
	"errors"
	pgmesh "github.com/clnv/pgmesh"
	"github.com/jackc/pgx/v5"
)

// ReadQuerier exposes generated read queries.
type ReadQuerier interface {
	// GetAccount executes the generated GetAccount query.
	GetAccount(ctx context.Context, arg *GetAccountParams) (*Account, error)
	// ListAccounts executes the generated ListAccounts query.
	ListAccounts(ctx context.Context) ([]*Account, error)
}

// WriteQuerier exposes generated write queries.
type WriteQuerier interface {
	// CopyAccounts executes the generated CopyAccounts query.
	CopyAccounts(ctx context.Context, arg []*CopyAccountsParams) (int64, error)
	// UpdateAccountName executes the generated UpdateAccountName query.
	UpdateAccountName(ctx context.Context, arg *UpdateAccountNameParams) (*Account, error)
	// UpsertAccount executes the generated UpsertAccount query.
	UpsertAccount(ctx context.Context, arg *UpsertAccountParams) (*Account, error)
}

// StoreQuerier combines the generated read and write query interfaces.
type StoreQuerier interface {
	ReadQuerier
	WriteQuerier
}

var _ ReadQuerier = (*ReadQueries)(nil)
var _ WriteQuerier = (*WriteQueries)(nil)
var _ StoreQuerier = (*StoreQueries)(nil)
var _ Querier = (*StoreQueries)(nil)

// ReadQueries exposes read-only generated queries.
type ReadQueries struct {
	main *Queries
}

// NewReadQueries creates a read-only query wrapper.
func NewReadQueries(database DBTX) *ReadQueries {
	return newReadQueries(New(database))
}

func newReadQueries(q *Queries) *ReadQueries {
	return &ReadQueries{main: q}
}

// WithTx returns a read wrapper that executes queries through tx.
func (q *ReadQueries) WithTx(tx pgx.Tx) *ReadQueries {
	return newReadQueries(q.main.WithTx(tx))
}

// GetAccount executes the generated GetAccount query.
func (q *ReadQueries) GetAccount(ctx context.Context, arg *GetAccountParams) (*Account, error) {
	rv0, err := q.main.GetAccount(ctx, arg)
	if err != nil {
		var zero0 *Account
		return zero0, err
	}
	return rv0, nil
}

// ListAccounts executes the generated ListAccounts query.
func (q *ReadQueries) ListAccounts(ctx context.Context) ([]*Account, error) {
	rv0, err := q.main.ListAccounts(ctx)
	if err != nil {
		var zero0 []*Account
		return zero0, err
	}
	return rv0, nil
}

// WriteQueries exposes primary-capable generated queries.
type WriteQueries struct {
	main    *Queries
	mirrors []*Queries
}

// NewWriteQueries creates a primary-capable query wrapper.
func NewWriteQueries(database DBTX) *WriteQueries {
	return newWriteQueries(New(database))
}

func newWriteQueries(q *Queries, mirrors ...*Queries) *WriteQueries {
	return &WriteQueries{main: q, mirrors: mirrors}
}

// WithTx returns a write wrapper that executes queries through tx.
func (q *WriteQueries) WithTx(tx pgx.Tx) *WriteQueries {
	return newWriteQueries(q.main.WithTx(tx))
}

// WithMirrors returns a copy that also writes to the supplied mirrors.
func (q *WriteQueries) WithMirrors(qs ...*WriteQueries) *WriteQueries {
	var mirrors []*Queries
	mirrors = append(mirrors, q.mirrors...)
	for _, mirror := range qs {
		if mirror == nil {
			continue
		}
		mirrors = append(mirrors, mirror.main)
		mirrors = append(mirrors, mirror.mirrors...)
	}
	return newWriteQueries(q.main, mirrors...)
}

func (q *WriteQueries) mirror(fn func(*Queries) error) error {
	for _, mirror := range q.mirrors {
		if err := fn(mirror); err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				continue
			}
			return err
		}
	}
	return nil
}

// CopyAccounts executes the generated CopyAccounts query.
func (q *WriteQueries) CopyAccounts(ctx context.Context, arg []*CopyAccountsParams) (int64, error) {
	rv0, err := q.main.CopyAccounts(ctx, arg)
	if err != nil {
		var zero0 int64
		return zero0, err
	}
	mirrorErr := q.mirror(func(mirror *Queries) error {
		_, err := mirror.CopyAccounts(ctx, arg)
		return err
	})
	return rv0, mirrorErr
}

// UpdateAccountName executes the generated UpdateAccountName query.
func (q *WriteQueries) UpdateAccountName(ctx context.Context, arg *UpdateAccountNameParams) (*Account, error) {
	rv0, err := q.main.UpdateAccountName(ctx, arg)
	if err != nil {
		var zero0 *Account
		return zero0, err
	}
	mirrorErr := q.mirror(func(mirror *Queries) error {
		_, err := mirror.UpdateAccountName(ctx, arg)
		return err
	})
	return rv0, mirrorErr
}

// UpsertAccount executes the generated UpsertAccount query.
func (q *WriteQueries) UpsertAccount(ctx context.Context, arg *UpsertAccountParams) (*Account, error) {
	rv0, err := q.main.UpsertAccount(ctx, arg)
	if err != nil {
		var zero0 *Account
		return zero0, err
	}
	mirrorErr := q.mirror(func(mirror *Queries) error {
		_, err := mirror.UpsertAccount(ctx, arg)
		return err
	})
	return rv0, mirrorErr
}

// StoreQueries combines read-only and primary-capable generated queries.
type StoreQueries struct {
	*ReadQueries
	*WriteQueries
}

// NewStoreQueries creates a combined query wrapper.
func NewStoreQueries(database DBTX) *StoreQueries {
	return newStoreQueries(New(database))
}

func newStoreQueries(q *Queries, mirrors ...*Queries) *StoreQueries {
	return &StoreQueries{
		ReadQueries:  newReadQueries(q),
		WriteQueries: newWriteQueries(q, mirrors...),
	}
}

// WithTx returns a store wrapper that executes queries through tx.
func (q *StoreQueries) WithTx(tx pgx.Tx) *StoreQueries {
	return newStoreQueries(q.WriteQueries.main.WithTx(tx))
}

// WithMirrors returns a copy that also writes to the supplied mirrors.
func (q *StoreQueries) WithMirrors(qs ...*StoreQueries) *StoreQueries {
	var mirrors []*Queries
	mirrors = append(mirrors, q.WriteQueries.mirrors...)
	for _, mirror := range qs {
		if mirror == nil || mirror.WriteQueries == nil {
			continue
		}
		mirrors = append(mirrors, mirror.WriteQueries.main)
		mirrors = append(mirrors, mirror.WriteQueries.mirrors...)
	}
	return newStoreQueries(q.WriteQueries.main, mirrors...)
}

// NewStoreNode creates a pgmesh node backed by database.
func NewStoreNode(database DBTX) pgmesh.Node[*ReadQueries, *StoreQueries] {
	queries := New(database)
	return pgmesh.NewNode(newReadQueries(queries), newStoreQueries(queries))
}

// ShardResolver resolves generated query parameters to shard keys.
type ShardResolver[SK any] interface {
	// Tenant resolves the "tenant" shard route.
	Tenant(tenantID int64) SK
}

type routeOptions struct {
	primary bool
	tx      pgx.Tx
}

// RouteOption customizes routing for one generated query call.
type RouteOption func(*routeOptions)

// ReadFromPrimary routes a read query to the shard's primary.
func ReadFromPrimary() RouteOption {
	return func(options *routeOptions) { options.primary = true }
}

// WithTx routes a query through tx and suppresses write mirrors.
func WithTx(tx pgx.Tx) RouteOption {
	return func(options *routeOptions) { options.tx = tx }
}

func applyRouteOptions(options ...RouteOption) routeOptions {
	var result routeOptions
	for _, option := range options {
		if option != nil {
			option(&result)
		}
	}
	return result
}

// ShardedQueries routes generated queries through a pgmesh mesh.
type ShardedQueries[SK any] struct {
	mesh     *pgmesh.Mesh[*ReadQueries, *StoreQueries, SK]
	resolver ShardResolver[SK]
}

// NewShardedQueries creates a routed query facade.
func NewShardedQueries[SK any](mesh *pgmesh.Mesh[*ReadQueries, *StoreQueries, SK], resolver ShardResolver[SK]) *ShardedQueries[SK] {
	return &ShardedQueries[SK]{mesh: mesh, resolver: resolver}
}

// GetAccount executes the generated query on its resolved shard.
func (q *ShardedQueries[SK]) GetAccount(ctx context.Context, arg *GetAccountParams, routeOptions ...RouteOption) (*Account, error) {
	ctx, queryTrace := q.mesh.StartQueryTrace(ctx, "GetAccount", pgmesh.QueryKindRead)
	var queryErr error
	defer func() { queryTrace.End(queryErr) }()
	shardKey := q.resolver.Tenant(arg.TenantID)
	shard, err := q.mesh.Shard(shardKey)
	if err != nil {
		queryErr = err
		var zero0 *Account
		return zero0, err
	}
	options := applyRouteOptions(routeOptions...)
	if options.tx != nil {
		queryTrace.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction, 0)
		var rv0 *Account
		rv0, queryErr = shard.Write().WithTx(options.tx).GetAccount(ctx, arg)
		return rv0, queryErr
	}
	if options.primary {
		queryTrace.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary, 0)
		var rv0 *Account
		rv0, queryErr = shard.Write().GetAccount(ctx, arg)
		return rv0, queryErr
	}
	queryTrace.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead, 0)
	var rv0 *Account
	rv0, queryErr = shard.Read().GetAccount(ctx, arg)
	return rv0, queryErr
}

// UpdateAccountName executes the generated query on its resolved shard.
func (q *ShardedQueries[SK]) UpdateAccountName(ctx context.Context, arg *UpdateAccountNameParams, routeOptions ...RouteOption) (*Account, error) {
	ctx, queryTrace := q.mesh.StartQueryTrace(ctx, "UpdateAccountName", pgmesh.QueryKindWrite)
	var queryErr error
	defer func() { queryTrace.End(queryErr) }()
	shardKey := q.resolver.Tenant(arg.TenantID)
	shard, err := q.mesh.Shard(shardKey)
	if err != nil {
		queryErr = err
		var zero0 *Account
		return zero0, err
	}
	options := applyRouteOptions(routeOptions...)
	target := shard.Write()
	mode := pgmesh.RouteModePrimary
	writeMirrorCount := shard.WriteMirrorCount()
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
		writeMirrorCount = 0
	}
	queryTrace.SetRoute(shard.VShardIndex(), shard.Name(), mode, writeMirrorCount)
	var rv0 *Account
	rv0, queryErr = target.UpdateAccountName(ctx, arg)
	return rv0, queryErr
}

// UpsertAccount executes the generated query on its resolved shard.
func (q *ShardedQueries[SK]) UpsertAccount(ctx context.Context, arg *UpsertAccountParams, routeOptions ...RouteOption) (*Account, error) {
	ctx, queryTrace := q.mesh.StartQueryTrace(ctx, "UpsertAccount", pgmesh.QueryKindWrite)
	var queryErr error
	defer func() { queryTrace.End(queryErr) }()
	shardKey := q.resolver.Tenant(arg.TenantID)
	shard, err := q.mesh.Shard(shardKey)
	if err != nil {
		queryErr = err
		var zero0 *Account
		return zero0, err
	}
	options := applyRouteOptions(routeOptions...)
	target := shard.Write()
	mode := pgmesh.RouteModePrimary
	writeMirrorCount := shard.WriteMirrorCount()
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
		writeMirrorCount = 0
	}
	queryTrace.SetRoute(shard.VShardIndex(), shard.Name(), mode, writeMirrorCount)
	var rv0 *Account
	rv0, queryErr = target.UpsertAccount(ctx, arg)
	return rv0, queryErr
}
