// Code generated by pgmesh. DO NOT EDIT.

package samepackage

import (
	"context"
)

// readQuerier exposes generated read queries.
type readQuerier interface {
	// GetAnalysis executes the generated GetAnalysis query.
	GetAnalysis(ctx context.Context, arg *GetAnalysisParams) (*Analysis, error)
	// GetTenantUserAnalysis executes the generated GetTenantUserAnalysis query.
	GetTenantUserAnalysis(ctx context.Context, arg *GetTenantUserAnalysisParams) (*GetTenantUserAnalysisRow, error)
	// GetUser executes the generated GetUser query.
	GetUser(ctx context.Context, arg *GetUserParams) (*User, error)
	// ListP2PMessageIDsByChat executes the generated ListP2PMessageIDsByChat query.
	ListP2PMessageIDsByChat(ctx context.Context, arg *ListP2PMessageIDsByChatParams) ([]interface{}, error)
	// ListP2PMessagesByChat executes the generated ListP2PMessagesByChat query.
	ListP2PMessagesByChat(ctx context.Context, arg *ListP2PMessagesByChatParams) ([]*Message, error)
}

// writeQuerier exposes generated write queries.
type writeQuerier interface {
	// CreateUser executes the generated CreateUser query.
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	// UpdateUserName executes the generated UpdateUserName query.
	UpdateUserName(ctx context.Context, arg *UpdateUserNameParams) (*User, error)
}

// Store is the topology-independent generated query API.
type Store interface {
	// Analyses returns the Analyses query group.
	Analyses() Analyses
	// QueryMessage returns the QueryMessage query group.
	QueryMessage() QueryMessage
	// Users returns the Users query group.
	Users() Users
}

var _ readQuerier = (*readQueries)(nil)
var _ writeQuerier = (*writeQueries)(nil)
var _ Querier = (*queryStore)(nil)

// ShardResolver resolves generated query parameters to shard keys.
type ShardResolver[SK any] interface {
	// Messagekey resolves the "messageKey" shard route.
	Messagekey(userID int64, toUserOrGroupID int64, inGroup bool) SK
	// Tenant resolves the "tenant" shard route.
	Tenant(tenantID int64) SK
}
